"""refile around ssvc

Revision ID: 1fc28876e6e9
Revises: 145f9cc8c891
Create Date: 2024-08-30 03:08:48.237731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fc28876e6e9'
down_revision = '145f9cc8c891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('system_exposure', sa.Enum('OPEN', 'CONTROLLED', 'SMALL', name='systemexposureenum'), server_default='open', nullable=False))
    op.add_column('service', sa.Column('safety_impact', sa.Enum('CATASTROPHIC', 'CRITICAL', 'MARGINAL', 'NEGLIGIBLE', name='safetyimpactenum'), server_default='negligible', nullable=False))
    op.drop_column('service', 'exposure')
    op.alter_column('topic', 'automatable',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('YES', 'NO', name='automatableenum'),
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('topic', 'safety_impact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('safety_impact', postgresql.ENUM('CATASTROPHIC', 'HAZARDOUS', 'MAJOR', 'MINOR', 'NONE', name='safetyimpactenum'), server_default=sa.text("'CATASTROPHIC'::safetyimpactenum"), autoincrement=False, nullable=False))
    op.alter_column('topic', 'automatable',
               existing_type=sa.Enum('YES', 'NO', name='automatableenum'),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('service', sa.Column('exposure', postgresql.ENUM('OPEN', 'CONTROLLED', 'SMALL', name='exposureenum'), server_default=sa.text("'OPEN'::exposureenum"), autoincrement=False, nullable=False))
    op.drop_column('service', 'safety_impact')
    op.drop_column('service', 'system_exposure')
    # ### end Alembic commands ###
