"""delete update_at in ticket table and unique of ticket_id in alert table

Revision ID: 7842ab8d58ec
Revises: e4ba4affc44f
Create Date: 2024-09-06 04:06:25.744826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7842ab8d58ec'
down_revision = 'e4ba4affc44f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_ticket_id', table_name='alert')
    op.create_index(op.f('ix_alert_ticket_id'), 'alert', ['ticket_id'], unique=False)
    op.drop_column('ticket', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_alert_ticket_id'), table_name='alert')
    op.create_index('ix_alert_ticket_id', 'alert', ['ticket_id'], unique=True)
    # ### end Alembic commands ###
