"""delete_threat_impact

Revision ID: 4912bc5835e5
Revises: 884b692bb1e6
Create Date: 2024-12-13 01:01:34.420806

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4912bc5835e5"
down_revision = "884b692bb1e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "threat_impact")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic",
        sa.Column(
            "threat_impact",
            sa.INTEGER(),
            server_default=sa.text("3"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column("topic", "threat_impact", server_default=None)
    # ### end Alembic commands ###
