"""add service keywords

Revision ID: 145f9cc8c891
Revises: 734970d141c8
Create Date: 2024-08-20 06:34:47.803559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145f9cc8c891'
down_revision = '734970d141c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('keywords', sa.ARRAY(sa.String(length=255)), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'keywords')
    # ### end Alembic commands ###
