"""add-updateat-in-service

Revision ID: dcab72f536f6
Revises: 55bb39ec2d69
Create Date: 2024-07-12 00:03:55.753011

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dcab72f536f6"
down_revision = "55bb39ec2d69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service", sa.Column("sbom_uploaded_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "sbom_uploaded_at")
    # ### end Alembic commands ###
