"""remove PTeamTag

Revision ID: d70c6355860e
Revises: 32ac32cc3d89
Create Date: 2024-02-20 05:50:32.734577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd70c6355860e'
down_revision = '32ac32cc3d89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pteamtag_pteam_id', table_name='pteamtag')
    op.drop_index('ix_pteamtag_tag_id', table_name='pteamtag')
    op.drop_table('pteamtag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pteamtag',
    sa.Column('pteam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('refs', postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pteam_id'], ['pteam.pteam_id'], name='pteamtag_pteam_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], name='pteamtag_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pteam_id', 'tag_id', name='pteamtag_pkey')
    )
    op.create_index('ix_pteamtag_tag_id', 'pteamtag', ['tag_id'], unique=False)
    op.create_index('ix_pteamtag_pteam_id', 'pteamtag', ['pteam_id'], unique=False)
    # ### end Alembic commands ###
