"""delete slack_webhook_url column in pteam and ateam table

Revision ID: bea1dc749c90
Revises: 8df12f0653b8
Create Date: 2024-03-07 00:56:25.446177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea1dc749c90'
down_revision = '8df12f0653b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ateam', 'slack_webhook_url')
    op.drop_column('pteam', 'slack_webhook_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pteam', sa.Column('slack_webhook_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('ateam', sa.Column('slack_webhook_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
