"""add uniqueConstraint

Revision ID: 4479f2acf45e
Revises: 461c9acd767e
Create Date: 2025-06-26 01:07:11.206344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4479f2acf45e'
down_revision = '461c9acd767e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('affect_vuln_id_affected_name_ecosystem_key', 'affect', ['vuln_id', 'affected_name', 'ecosystem'])
    op.drop_constraint('package_name_ecosystem_key', 'package', type_='unique')
    op.create_unique_constraint('package_name_ecosystem_source_name_key', 'package', ['name', 'ecosystem', 'source_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('package_name_ecosystem_source_name_key', 'package', type_='unique')
    op.create_unique_constraint('package_name_ecosystem_key', 'package', ['name', 'ecosystem'])
    op.drop_constraint('affect_vuln_id_affected_name_ecosystem_key', 'affect', type_='unique')
    # ### end Alembic commands ###
