"""delete VulunAction table

Revision ID: 7c815bcb9a0a
Revises: ebf329b1b534
Create Date: 2025-12-04 06:07:20.151831

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7c815bcb9a0a"
down_revision = "ebf329b1b534"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vulnaction_vuln_id"), table_name="vulnaction")
    op.drop_table("vulnaction")
    op.drop_column("actionlog", "action_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "actionlog",
        sa.Column("action_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    )
    op.create_table(
        "vulnaction",
        sa.Column("action_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("vuln_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("action", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("recommended", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vuln_id"], ["vuln.vuln_id"], name=op.f("vulnaction_vuln_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("action_id", name=op.f("vulnaction_pkey")),
    )
    op.add_column(
        "vulnaction",
        sa.Column(
            "action_type",
            sa.Enum(
                "elimination",
                "transfer",
                "mitigation",
                "acceptance",
                "detection",
                "rejection",
                name="actiontype",
            ),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_vulnaction_vuln_id"), "vulnaction", ["vuln_id"], unique=False)
    # ### end Alembic commands ###
