"""add updated_at and delete created_at

Revision ID: 8d90dc6aa717
Revises: 9dac8976dadb
Create Date: 2025-10-17 01:27:32.559653

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8d90dc6aa717"
down_revision = "9dac8976dadb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticket", "created_at")
    op.add_column(
        "ticketstatus",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.execute(
        "ALTER TABLE ticketstatus ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'"
    )
    op.execute("UPDATE ticketstatus SET updated_at = created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticketstatus", "updated_at")
    op.add_column(
        "ticket",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.execute(
        "ALTER TABLE ticket ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC'"
    )
    op.execute(
        "UPDATE ticket SET created_at = t.created_at FROM ticketstatus AS t WHERE ticket.ticket_id = t.ticket_id"
    )
    # ### end Alembic commands ###
