"""delete VulunAction table

Revision ID: c6d48363d215
Revises: ebf329b1b534
Create Date: 2025-12-04 07:17:01.826993

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c6d48363d215"
down_revision = "ebf329b1b534"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vulnaction_vuln_id"), table_name="vulnaction")
    op.drop_table("vulnaction")
    op.drop_column("actionlog", "recommended")
    op.drop_column("actionlog", "action_type")
    op.drop_column("actionlog", "action_id")
    op.execute("DROP TYPE actiontype;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    action_type = sa.Enum(
        "elimination",
        "transfer",
        "mitigation",
        "acceptance",
        "detection",
        "rejection",
        name="actiontype",
    )
    action_type.create(connection)
    op.add_column(
        "actionlog",
        sa.Column("action_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    )

    ## action_type in actionlog table
    op.add_column(
        "actionlog",
        sa.Column(
            "action_type",
            postgresql.ENUM(
                "elimination",
                "transfer",
                "mitigation",
                "acceptance",
                "detection",
                "rejection",
                name="actiontype",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.execute(
        """
       UPDATE actionlog
       SET action_type = 'elimination'
       """
    )
    op.alter_column(
        "actionlog",
        "action_type",
        existing_type=postgresql.ENUM(
            "elimination",
            "transfer",
            "mitigation",
            "acceptance",
            "detection",
            "rejection",
            name="actiontype",
        ),
        nullable=False,
    )

    ## recommended in actionlog table
    op.add_column(
        "actionlog", sa.Column("recommended", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.execute(
        """
       UPDATE actionlog
       SET recommended = True
       """
    )
    op.alter_column(
        "actionlog",
        "recommended",
        nullable=False,
    )

    ## vulnaction table
    op.create_table(
        "vulnaction",
        sa.Column("action_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("vuln_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("action", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("recommended", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vuln_id"], ["vuln.vuln_id"], name=op.f("vulnaction_vuln_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("action_id", name=op.f("vulnaction_pkey")),
    )
    op.add_column(
        "vulnaction",
        sa.Column(
            "action_type",
            postgresql.ENUM(
                "elimination",
                "transfer",
                "mitigation",
                "acceptance",
                "detection",
                "rejection",
                name="actiontype",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_vulnaction_vuln_id"), "vulnaction", ["vuln_id"], unique=False)
    # ### end Alembic commands ###
