"""add nulls_not_distinct in package table

Revision ID: 10eec183211d
Revises: 8d90dc6aa717
Create Date: 2025-10-24 06:55:10.554976

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "10eec183211d"
down_revision = "8d90dc6aa717"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("package_name_ecosystem_source_name_key"), "package", type_="unique")
    op.create_unique_constraint(
        "package_name_ecosystem_source_name_key",
        "package",
        ["name", "ecosystem", "source_name"],
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("package_name_ecosystem_source_name_key", "package", type_="unique")
    op.create_unique_constraint(
        op.f("package_name_ecosystem_source_name_key"),
        "package",
        ["name", "ecosystem", "source_name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
