"""add accountdefaultpteam table

Revision ID: 8bd3d29afe74
Revises: 10eec183211d
Create Date: 2025-10-25 06:54:14.421567

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bd3d29afe74"
down_revision = "10eec183211d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accountdefaultpteam",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("default_pteam_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["default_pteam_id"], ["pteam.pteam_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["account.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_accountdefaultpteam_default_pteam_id"),
        "accountdefaultpteam",
        ["default_pteam_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_accountdefaultpteam_user_id"), "accountdefaultpteam", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accountdefaultpteam_user_id"), table_name="accountdefaultpteam")
    op.drop_index(op.f("ix_accountdefaultpteam_default_pteam_id"), table_name="accountdefaultpteam")
    op.drop_table("accountdefaultpteam")
    # ### end Alembic commands ###
