"""add updated_at to the TicketStatus table

Revision ID: 036d4e3b3aac
Revises: 9dac8976dadb
Create Date: 2025-10-16 05:27:21.301723

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "036d4e3b3aac"
down_revision = "9dac8976dadb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "ticketstatus",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.execute(
        "ALTER TABLE ticketstatus ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC'"
    )
    op.execute("UPDATE ticketstatus SET updated_at = created_at")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticketstatus", "updated_at")
    # ### end Alembic commands ###
