"""add_vuln_matching_ecosystem_to_package

Revision ID: b68d354ff0bc
Revises: 4479f2acf45e
Create Date: 2025-07-10 00:19:38.639209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68d354ff0bc'
down_revision = '4479f2acf45e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('vuln_matching_ecosystem', sa.Text(), nullable=True))
    op.execute(
        "UPDATE package SET vuln_matching_ecosystem = ecosystem"
    )
    op.alter_column('package', 'vuln_matching_ecosystem', nullable=False)
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package', 'vuln_matching_ecosystem')
    # ### end Alembic commands ###
