"""add_eol

Revision ID: 9b57f247ce4c
Revises: c6d48363d215
Create Date: 2025-12-25 06:48:51.650283

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b57f247ce4c"
down_revision = "c6d48363d215"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ## create eolproduct
    op.create_table(
        "eolproduct",
        sa.Column("eol_product_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "product_category",
            sa.Enum("OS", "RUNTIME", "MIDDLEWARE", "PACKAGE", name="productcategoryenum"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_ecosystem", sa.Boolean(), nullable=False),
        sa.Column("matching_product_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("eol_product_id"),
    )

    ## create eolversion
    op.create_table(
        "eolversion",
        sa.Column("eol_version_id", sa.String(length=36), nullable=False),
        sa.Column("eol_product_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("eol_from", sa.Date(), nullable=False),
        sa.Column("matching_version", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["eol_product_id"], ["eolproduct.eol_product_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("eol_version_id"),
    )
    op.create_index(
        op.f("ix_eolversion_eol_product_id"), "eolversion", ["eol_product_id"], unique=False
    )

    ## create ecosystemeoldependency
    op.create_table(
        "ecosystemeoldependency",
        sa.Column("ecosystem_eol_dependency_id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.String(length=36), nullable=False),
        sa.Column("eol_version_id", sa.String(length=36), nullable=False),
        sa.Column("eol_notification_sent", sa.Boolean(), nullable=False, server_default="false"),
        sa.ForeignKeyConstraint(
            ["eol_version_id"], ["eolversion.eol_version_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.service_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ecosystem_eol_dependency_id"),
        sa.UniqueConstraint(
            "service_id",
            "eol_version_id",
            name="ecosystemeoldependency_service_id_eol_version_id_key",
        ),
    )
    op.create_index(
        op.f("ix_ecosystemeoldependency_eol_version_id"),
        "ecosystemeoldependency",
        ["eol_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ecosystemeoldependency_service_id"),
        "ecosystemeoldependency",
        ["service_id"],
        unique=False,
    )

    ## create packageeoldependency
    op.create_table(
        "packageeoldependency",
        sa.Column("package_eol_dependency_id", sa.String(length=36), nullable=False),
        sa.Column("dependency_id", sa.String(length=36), nullable=False),
        sa.Column("eol_version_id", sa.String(length=36), nullable=False),
        sa.Column("eol_notification_sent", sa.Boolean(), nullable=False, server_default="false"),
        sa.ForeignKeyConstraint(
            ["dependency_id"], ["dependency.dependency_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["eol_version_id"], ["eolversion.eol_version_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("package_eol_dependency_id"),
        sa.UniqueConstraint(
            "dependency_id",
            "eol_version_id",
            name="packageeoldependency_dependency_id_eol_version_id_key",
        ),
    )
    op.create_index(
        op.f("ix_packageeoldependency_dependency_id"),
        "packageeoldependency",
        ["dependency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_packageeoldependency_eol_version_id"),
        "packageeoldependency",
        ["eol_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_packageeoldependency_eol_version_id"), table_name="packageeoldependency")
    op.drop_index(op.f("ix_packageeoldependency_dependency_id"), table_name="packageeoldependency")
    op.drop_table("packageeoldependency")
    op.drop_index(op.f("ix_ecosystemeoldependency_service_id"), table_name="ecosystemeoldependency")
    op.drop_index(
        op.f("ix_ecosystemeoldependency_eol_version_id"), table_name="ecosystemeoldependency"
    )
    op.drop_table("ecosystemeoldependency")
    op.drop_index(op.f("ix_eolversion_eol_product_id"), table_name="eolversion")
    op.drop_table("eolversion")
    op.drop_table("eolproduct")

    # Drop the enum type
    sa.Enum(name="productcategoryenum").drop(op.get_bind())
    # ### end Alembic commands ###
