"""add_insight

Revision ID: 393003f456f5
Revises: a529a44388db
Create Date: 2025-08-08 08:04:05.788384

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "393003f456f5"
down_revision = "a529a44388db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objectcategory",
        sa.Column("object_category_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("object_category_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "insight",
        sa.Column("insight_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reasoning_and_planing", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.ticket_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("insight_id"),
    )
    op.create_index(op.f("ix_insight_ticket_id"), "insight", ["ticket_id"], unique=True)
    op.create_table(
        "affectedobject",
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("insight_id", sa.String(length=36), nullable=False),
        sa.Column("object_category_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["insight_id"], ["insight.insight_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["object_category_id"],
            ["objectcategory.object_category_id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
    )
    op.create_index(
        op.f("ix_affectedobject_insight_id"), "affectedobject", ["insight_id"], unique=False
    )
    op.create_index(
        op.f("ix_affectedobject_object_category_id"),
        "affectedobject",
        ["object_category_id"],
        unique=False,
    )
    op.create_table(
        "insightreference",
        sa.Column("insight_reference_id", sa.String(length=36), nullable=False),
        sa.Column("insight_id", sa.String(length=36), nullable=False),
        sa.Column("link_text", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["insight_id"], ["insight.insight_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("insight_reference_id"),
    )
    op.create_index(
        op.f("ix_insightreference_insight_id"), "insightreference", ["insight_id"], unique=False
    )
    op.create_table(
        "threatscenario",
        sa.Column("threat_scenario_id", sa.String(length=36), nullable=False),
        sa.Column("insight_id", sa.String(length=36), nullable=False),
        sa.Column(
            "impact_category",
            sa.Enum(
                "DAMAGE_TO_PROPERTY",
                "DENIAL_OF_CONTROL",
                "DENIAL_OF_VIEW",
                "LOSS_OF_AVAILABILITY",
                "LOSS_OF_CONTROL",
                "LOSS_OF_PRODUCTIVITY_AND_REVENUE",
                "LOSS_OF_PROTECTION",
                "LOSS_OF_SAFETY",
                "LOSS_OF_VIEW",
                "MANIPULATION_OF_CONTROL",
                "MANIPULATION_OF_VIEW",
                "THEFT_OF_OPERATIONAL_INFORMATION",
                name="impactcategoryenum",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["insight_id"], ["insight.insight_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("threat_scenario_id"),
    )
    op.create_index(
        op.f("ix_threatscenario_insight_id"), "threatscenario", ["insight_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threatscenario_insight_id"), table_name="threatscenario")
    op.drop_table("threatscenario")
    op.drop_index(op.f("ix_insightreference_insight_id"), table_name="insightreference")
    op.drop_table("insightreference")
    op.drop_index(op.f("ix_affectedobject_object_category_id"), table_name="affectedobject")
    op.drop_index(op.f("ix_affectedobject_insight_id"), table_name="affectedobject")
    op.drop_table("affectedobject")
    op.drop_index(op.f("ix_insight_ticket_id"), table_name="insight")
    op.drop_table("insight")
    op.drop_table("objectcategory")

    # Drop the enum type
    sa.Enum(name="impactcategoryenum").drop(op.get_bind())
    # ### end Alembic commands ###
