"""add_asset

Revision ID: fc951d39ced5
Revises: 993a4b0c7487
Create Date: 2026-04-16 01:09:53.429254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc951d39ced5'
down_revision = '993a4b0c7487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('ip_addresses', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_asset_service_id'), 'asset', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_service_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
