"""add sbomuploadprogress  table

Revision ID: 5f2a38a39a45
Revises: bcbd2d04d6f5
Create Date: 2026-03-13 01:04:18.975044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2a38a39a45'
down_revision = 'bcbd2d04d6f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sbomuploadprogress',
    sa.Column('sbom_upload_progress_id', sa.String(length=36), nullable=False),
    sa.Column('pteam_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('progress_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pteam_id'], ['pteam.pteam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sbom_upload_progress_id')
    )
    op.create_index(op.f('ix_sbomuploadprogress_pteam_id'), 'sbomuploadprogress', ['pteam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sbomuploadprogress_pteam_id'), table_name='sbomuploadprogress')
    op.drop_table('sbomuploadprogress')
    # ### end Alembic commands ###
