"""add_location

Revision ID: 815b28131cfb
Revises: fc951d39ced5
Create Date: 2026-06-22 01:22:27.906486

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "815b28131cfb"
down_revision = "fc951d39ced5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("asset", sa.Column("country_code", sa.String(length=2), nullable=True))
    op.add_column("asset", sa.Column("address", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset", "address")
    op.drop_column("asset", "country_code")
    # ### end Alembic commands ###
