"""add sbom_upload_progress table

Revision ID: 7921a5a3790c
Revises: bcbd2d04d6f5
Create Date: 2026-03-12 02:13:55.942070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7921a5a3790c'
down_revision = 'bcbd2d04d6f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sbomuploadprogress',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('progress_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_sbomuploadprogress_service_id'), 'sbomuploadprogress', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sbomuploadprogress_service_id'), table_name='sbomuploadprogress')
    op.drop_table('sbomuploadprogress')
    # ### end Alembic commands ###
