"""del_matching_name

Revision ID: bcbd2d04d6f5
Revises: 9b57f247ce4c
Create Date: 2026-02-25 01:48:05.812801

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bcbd2d04d6f5"
down_revision = "9b57f247ce4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("eolproduct", "matching_name")
    op.drop_column("eolversion", "matching_version")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "eolversion", sa.Column("matching_version", sa.VARCHAR(length=255), nullable=True)
    )
    op.add_column("eolproduct", sa.Column("matching_name", sa.VARCHAR(length=255), nullable=True))

    op.execute(
        """
        UPDATE eolproduct
        SET matching_name = name
        """
    )
    op.execute(
        """
        UPDATE eolversion
        SET matching_version = version
        """
    )

    op.alter_column("eolversion", "matching_version", nullable=False)
    op.alter_column("eolproduct", "matching_name", nullable=False)

    # ### end Alembic commands ###
