"""add_location

Revision ID: 815b28131cfb
Revises: fc951d39ced5
Create Date: 2026-06-22 01:22:27.906486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815b28131cfb'
down_revision = 'fc951d39ced5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_accountdefaultpteam_user_id'), 'accountdefaultpteam', ['user_id'], unique=False)
    op.add_column('asset', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('asset', sa.Column('address', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_pteammail_pteam_id'), 'pteammail', ['pteam_id'], unique=False)
    op.create_index(op.f('ix_pteamslack_pteam_id'), 'pteamslack', ['pteam_id'], unique=False)
    op.create_index(op.f('ix_servicethumbnail_service_id'), 'servicethumbnail', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicethumbnail_service_id'), table_name='servicethumbnail')
    op.drop_index(op.f('ix_pteamslack_pteam_id'), table_name='pteamslack')
    op.drop_index(op.f('ix_pteammail_pteam_id'), table_name='pteammail')
    op.drop_column('asset', 'address')
    op.drop_column('asset', 'country_code')
    op.drop_index(op.f('ix_accountdefaultpteam_user_id'), table_name='accountdefaultpteam')
    # ### end Alembic commands ###
