"""delete index

Revision ID: 993a4b0c7487
Revises: 5f2a38a39a45
Create Date: 2026-03-26 09:13:58.957429

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "993a4b0c7487"
down_revision = "5f2a38a39a45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accountdefaultpteam_user_id"), table_name="")
    op.drop_index(op.f("ix_pteammail_pteam_id"), table_name="pteammail")
    op.drop_index(op.f("ix_pteamslack_pteam_id"), table_name="pteamslack")
    op.drop_index(op.f("ix_servicethumbnail_service_id"), table_name="servicethumbnail")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_servicethumbnail_service_id"), "servicethumbnail", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_pteamslack_pteam_id"), "pteamslack", ["pteam_id"], unique=False)
    op.create_index(op.f("ix_pteammail_pteam_id"), "pteammail", ["pteam_id"], unique=False)
    op.create_index(
        op.f("ix_accountdefaultpteam_user_id"), "accountdefaultpteam", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
