"""add dependency_id and delete tag_id and service_id in threat table

Revision ID: 373a66ea574d
Revises: f196d35697d4
Create Date: 2024-05-21 06:54:24.183981

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "373a66ea574d"
down_revision = "f196d35697d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dependency",
        sa.Column("dependency_id", sa.VARCHAR(length=36), autoincrement=False),
    )
    op.execute(
        """
       UPDATE dependency
       SET dependency_id = gen_random_uuid()
       """
    )
    op.drop_constraint("dependency_pkey", table_name="dependency")
    op.create_primary_key("dependency_pkey", "dependency", ["dependency_id"])

    op.drop_index(op.f("ix_alert_ticket_id"), table_name="alert")
    op.drop_table("alert")
    op.drop_index(op.f("ix_currentticketstatus_ticket_id"), table_name="currentticketstatus")
    op.drop_index(op.f("ix_currentticketstatus_status_id"), table_name="currentticketstatus")
    op.drop_table("currentticketstatus")
    op.drop_index(op.f("ix_ticketstatus_ticket_id"), table_name="ticketstatus")
    op.drop_table("ticketstatus")
    op.drop_index(op.f("ix_ticket_threat_id"), table_name="ticket")
    op.drop_table("ticket")
    op.drop_index(op.f("ix_threat_topic_id"), table_name="threat")
    op.drop_index(op.f("ix_threat_tag_id"), table_name="threat")
    op.drop_index(op.f("ix_threat_service_id"), table_name="threat")
    op.drop_table("threat")

    op.create_table(
        "threat",
        sa.Column("threat_id", sa.String(length=36), nullable=False),
        sa.Column("dependency_id", sa.String(length=36), nullable=False),
        sa.Column("topic_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["dependency_id"], ["dependency.dependency_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.topic_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("threat_id"),
        sa.UniqueConstraint("dependency_id", "topic_id", name="threat_dependency_id_topic_id_key"),
    )
    op.create_index(op.f("ix_threat_topic_id"), "threat", ["topic_id"], unique=False)
    op.create_index(op.f("ix_threat_dependency_id"), "threat", ["dependency_id"], unique=False)
    op.create_table(
        "ticket",
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("threat_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["threat_id"], ["threat.threat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(op.f("ix_ticket_threat_id"), "ticket", ["threat_id"], unique=True)
    op.add_column(
        "ticket",
        sa.Column(
            "ssvc_deployer_priority", type_=sa.Enum(name="ssvcdeployerpriorityenum"), nullable=True
        ),
    )

    op.create_table(
        "ticketstatus",
        sa.Column("status_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("logging_ids", sa.ARRAY(sa.String(length=36)), nullable=False),
        sa.Column("assignees", sa.ARRAY(sa.String(length=36)), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.ticket_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("status_id"),
    )
    op.create_index(op.f("ix_ticketstatus_ticket_id"), "ticketstatus", ["ticket_id"], unique=False)
    op.add_column(
        "ticketstatus",
        sa.Column("topic_status", type_=sa.Enum(name="topicstatustype"), nullable=False),
    )

    op.create_table(
        "currentticketstatus",
        sa.Column("current_status_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("status_id", sa.String(length=36), nullable=True),
        sa.Column("threat_impact", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["pteamtopictagstatus.status_id"],
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.ticket_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("current_status_id"),
    )
    op.create_index(
        op.f("ix_currentticketstatus_status_id"), "currentticketstatus", ["status_id"], unique=False
    )
    op.create_index(
        op.f("ix_currentticketstatus_ticket_id"), "currentticketstatus", ["ticket_id"], unique=True
    )
    op.add_column(
        "currentticketstatus",
        sa.Column("topic_status", type_=sa.Enum(name="topicstatustype"), nullable=True),
    )

    op.create_table(
        "alert",
        sa.Column("alert_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=True),
        sa.Column(
            "alerted_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("alert_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.ticket_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    op.create_index(op.f("ix_alert_ticket_id"), "alert", ["ticket_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_ticket_id"), table_name="alert")
    op.drop_table("alert")
    op.drop_index(op.f("ix_currentticketstatus_ticket_id"), table_name="currentticketstatus")
    op.drop_index(op.f("ix_currentticketstatus_status_id"), table_name="currentticketstatus")
    op.drop_table("currentticketstatus")
    op.drop_index(op.f("ix_ticketstatus_ticket_id"), table_name="ticketstatus")
    op.drop_table("ticketstatus")
    op.drop_index(op.f("ix_ticket_threat_id"), table_name="ticket")
    op.drop_table("ticket")
    op.drop_index(op.f("ix_threat_topic_id"), table_name="threat")
    op.drop_index(op.f("ix_threat_dependency_id"), table_name="threat")
    op.drop_table("threat")

    op.create_table(
        "threat",
        sa.Column("threat_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.String(length=36), nullable=False),
        sa.Column("topic_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["service.service_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.tag_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.topic_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("threat_id"),
        sa.UniqueConstraint(
            "tag_id", "service_id", "topic_id", name="threat_tag_id_service_id_topic_id_key"
        ),
    )
    op.create_index(op.f("ix_threat_service_id"), "threat", ["service_id"], unique=False)
    op.create_index(op.f("ix_threat_tag_id"), "threat", ["tag_id"], unique=False)
    op.create_index(op.f("ix_threat_topic_id"), "threat", ["topic_id"], unique=False)

    op.create_table(
        "ticket",
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("threat_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["threat_id"], ["threat.threat_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(op.f("ix_ticket_threat_id"), "ticket", ["threat_id"], unique=True)
    op.add_column(
        "ticket",
        sa.Column(
            "ssvc_deployer_priority", type_=sa.Enum(name="ssvcdeployerpriorityenum"), nullable=True
        ),
    )

    op.create_table(
        "ticketstatus",
        sa.Column("status_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("logging_ids", sa.ARRAY(sa.String(length=36)), nullable=False),
        sa.Column("assignees", sa.ARRAY(sa.String(length=36)), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.ticket_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("status_id"),
    )
    op.create_index(op.f("ix_ticketstatus_ticket_id"), "ticketstatus", ["ticket_id"], unique=False)
    op.add_column(
        "ticketstatus",
        sa.Column("topic_status", type_=sa.Enum(name="topicstatustype"), nullable=False),
    )

    op.create_table(
        "currentticketstatus",
        sa.Column("current_status_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("status_id", sa.String(length=36), nullable=True),
        sa.Column("threat_impact", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["pteamtopictagstatus.status_id"],
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.ticket_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("current_status_id"),
    )
    op.create_index(
        op.f("ix_currentticketstatus_status_id"), "currentticketstatus", ["status_id"], unique=False
    )
    op.create_index(
        op.f("ix_currentticketstatus_ticket_id"), "currentticketstatus", ["ticket_id"], unique=True
    )
    op.add_column(
        "currentticketstatus",
        sa.Column("topic_status", type_=sa.Enum(name="topicstatustype"), nullable=True),
    )

    op.create_table(
        "alert",
        sa.Column("alert_id", sa.String(length=36), nullable=False),
        sa.Column("ticket_id", sa.String(length=36), nullable=True),
        sa.Column(
            "alerted_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("alert_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["ticket_id"], ["ticket.ticket_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    op.create_index(op.f("ix_alert_ticket_id"), "alert", ["ticket_id"], unique=True)

    op.drop_constraint("dependency_pkey", "dependency", type_="primary")
    op.create_primary_key(
        "dependency_pkey", "dependency", ["service_id", "tag_id", "version", "target"]
    )
    op.drop_column("dependency", "dependency_id")
    # ### end Alembic commands ###
