"""expand for SSVC

Revision ID: 3a0582573298
Revises: 450a40c2385b
Create Date: 2024-05-10 01:24:33.091285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0582573298'
down_revision = '450a40c2385b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    mission_impact_enum = sa.Enum('MISSION_FAILURE', 'MEF_FAILURE', 'CRIPPLED', 'DEGRADED', 'NONE', name='missionimpactenum')
    mission_impact_enum.create(connection)
    exposure_enum = sa.Enum('OPEN', 'CONTROLLED', 'SMALL', name='exposureenum')
    exposure_enum.create(connection)
    safety_impact_enum = sa.Enum('CATASTROPHIC', 'HAZARDOUS', 'MAJOR', 'MINOR', 'NONE', name='safetyimpactenum')
    safety_impact_enum.create(connection)
    exploitation_enum = sa.Enum('ACTIVE', 'POC', 'NONE', name='exploitationenum')
    exploitation_enum.create(connection)
    op.create_table('ticket',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('threat_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ssvc_deployer_priority', sa.Enum('IMMEDIATE', 'OUT_OF_CYCLE', 'SCHEDULED', 'DEFER', name='ssvcdeployerpriorityenum'), nullable=True),
    sa.ForeignKeyConstraint(['threat_id'], ['threat.threat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_ticket_threat_id'), 'ticket', ['threat_id'], unique=True)
    op.create_table('alert',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('alerted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('alert_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alert_ticket_id'), 'alert', ['ticket_id'], unique=True)
    op.add_column('dependency', sa.Column('dependency_mission_impact', mission_impact_enum, server_default=None, nullable=True))
    op.add_column('service', sa.Column('exposure', exposure_enum, server_default='OPEN', nullable=False))
    op.add_column('service', sa.Column('service_mission_impact', mission_impact_enum, server_default='MISSION_FAILURE', nullable=False))
    op.add_column('topic', sa.Column('safety_impact', safety_impact_enum, server_default='CATASTROPHIC', nullable=False))
    op.add_column('topic', sa.Column('exploitation', exploitation_enum, server_default='ACTIVE', nullable=False))
    op.add_column('topic', sa.Column('automatable', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    op.add_column('topic', sa.Column('hint_for_action', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'hint_for_action')
    op.drop_column('topic', 'automatable')
    op.drop_column('topic', 'exploitation')
    op.drop_column('topic', 'safety_impact')
    op.drop_column('service', 'service_mission_impact')
    op.drop_column('service', 'exposure')
    op.drop_column('dependency', 'dependency_mission_impact')
    op.drop_index(op.f('ix_alert_ticket_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_ticket_threat_id'), table_name='ticket')
    op.drop_table('ticket')
    connection = op.get_bind()
    sa.Enum(name="ssvcdeployerpriorityenum").drop(connection)
    sa.Enum(name="missionimpactenum").drop(connection)
    sa.Enum(name="exposureenum").drop(connection)
    sa.Enum(name="safetyimpactenum").drop(connection)
    sa.Enum(name="exploitationenum").drop(connection)
    # ### end Alembic commands ###
