"""obsolete CurrentTicketStatus

Revision ID: 3f1137b70d1a
Revises: c0ce4f1cf87a
Create Date: 2024-11-17 23:43:22.486338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f1137b70d1a'
down_revision = 'c0ce4f1cf87a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currentticketstatus_status_id', table_name='currentticketstatus')
    op.drop_index('ix_currentticketstatus_ticket_id', table_name='currentticketstatus')
    op.drop_table('currentticketstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currentticketstatus',
    sa.Column('current_status_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('threat_impact', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('topic_status', postgresql.ENUM('alerted', 'acknowledged', 'scheduled', 'completed', name='topicstatustype'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['ticketstatus.status_id'], name='currentticketstatus_status_id_fkey'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], name='currentticketstatus_ticket_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('current_status_id', name='currentticketstatus_pkey')
    )
    op.create_index('ix_currentticketstatus_ticket_id', 'currentticketstatus', ['ticket_id'], unique=True)
    op.create_index('ix_currentticketstatus_status_id', 'currentticketstatus', ['status_id'], unique=False)
    # ### end Alembic commands ###
