"""add threat table

Revision ID: 450a40c2385b
Revises: b51315587b5d
Create Date: 2024-04-26 07:46:31.076699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450a40c2385b'
down_revision = 'b51315587b5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat',
    sa.Column('threat_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_id'),
    sa.UniqueConstraint('tag_id', 'service_id', 'topic_id', name='threat_tag_id_service_id_topic_id_key')
    )
    op.create_index(op.f('ix_threat_service_id'), 'threat', ['service_id'], unique=False)
    op.create_index(op.f('ix_threat_tag_id'), 'threat', ['tag_id'], unique=False)
    op.create_index(op.f('ix_threat_topic_id'), 'threat', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_topic_id'), table_name='threat')
    op.drop_index(op.f('ix_threat_tag_id'), table_name='threat')
    op.drop_index(op.f('ix_threat_service_id'), table_name='threat')
    op.drop_table('threat')
    # ### end Alembic commands ###
