"""change_ondelete_to_cascade

Revision ID: 4765ef6b26ef
Revises: dcab72f536f6
Create Date: 2024-08-19 04:25:05.001507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4765ef6b26ef'
down_revision = 'dcab72f536f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ateamaccount_ateam_id_fkey', 'ateamaccount', type_='foreignkey')
    op.create_foreign_key('ateamaccount_ateam_id_fkey', 'ateamaccount', 'ateam', ['ateam_id'], ['ateam_id'], ondelete='CASCADE')
    op.drop_constraint('ateamauthority_ateam_id_fkey', 'ateamauthority', type_='foreignkey')
    op.create_foreign_key('ateamauthority_ateam_id_fkey', 'ateamauthority', 'ateam', ['ateam_id'], ['ateam_id'], ondelete='CASCADE')
    op.drop_constraint('ateaminvitation_ateam_id_fkey', 'ateaminvitation', type_='foreignkey')
    op.create_foreign_key('ateaminvitation_ateam_id_fkey', 'ateaminvitation', 'ateam', ['ateam_id'], ['ateam_id'], ondelete='CASCADE')
    op.drop_constraint('ateampteam_ateam_id_fkey', 'ateampteam', type_='foreignkey')
    op.create_foreign_key('ateampteam_ateam_id_fkey', 'ateampteam', 'ateam', ['ateam_id'], ['ateam_id'], ondelete='CASCADE')
    op.drop_constraint('ateamtopiccomment_ateam_id_fkey', 'ateamtopiccomment', type_='foreignkey')
    op.create_foreign_key('ateamtopiccomment_ateam_id_fkey', 'ateamtopiccomment', 'ateam', ['ateam_id'], ['ateam_id'], ondelete='CASCADE')
    op.drop_constraint('ateamwatchingrequest_ateam_id_fkey', 'ateamwatchingrequest', type_='foreignkey')
    op.create_foreign_key('ateamwatchingrequest_ateam_id_fkey', 'ateamwatchingrequest', 'ateam', ['ateam_id'], ['ateam_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ateamwatchingrequest_ateam_id_fkey', 'ateamwatchingrequest', type_='foreignkey')
    op.create_foreign_key('ateamwatchingrequest_ateam_id_fkey', 'ateamwatchingrequest', 'ateam', ['ateam_id'], ['ateam_id'])
    op.drop_constraint('ateamtopiccomment_ateam_id_fkey', 'ateamtopiccomment', type_='foreignkey')
    op.create_foreign_key('ateamtopiccomment_ateam_id_fkey', 'ateamtopiccomment', 'ateam', ['ateam_id'], ['ateam_id'])
    op.drop_constraint('ateampteam_ateam_id_fkey', 'ateampteam', type_='foreignkey')
    op.create_foreign_key('ateampteam_ateam_id_fkey', 'ateampteam', 'ateam', ['ateam_id'], ['ateam_id'])
    op.drop_constraint('ateaminvitation_ateam_id_fkey', 'ateaminvitation', type_='foreignkey')
    op.create_foreign_key('ateaminvitation_ateam_id_fkey', 'ateaminvitation', 'ateam', ['ateam_id'], ['ateam_id'])
    op.drop_constraint('ateamauthority_ateam_id_fkey', 'ateamauthority', type_='foreignkey')
    op.create_foreign_key('ateamauthority_ateam_id_fkey', 'ateamauthority', 'ateam', ['ateam_id'], ['ateam_id'])
    op.drop_constraint('ateamaccount_ateam_id_fkey', 'ateamaccount', type_='foreignkey')
    op.create_foreign_key('ateamaccount_ateam_id_fkey', 'ateamaccount', 'ateam', ['ateam_id'], ['ateam_id'])
    # ### end Alembic commands ###
