"""add cvss_v3_score

Revision ID: 4cc1242d7d3f
Revises: 79208ca4528e
Create Date: 2024-12-04 06:30:31.634509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc1242d7d3f'
down_revision = '79208ca4528e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('cvss_v3_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'cvss_v3_score')
    # ### end Alembic commands ###
