"""add PTeamTagReference

Revision ID: 522bad1d2d9c
Revises: 38cbbe8bb594
Create Date: 2024-02-08 04:34:29.178042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522bad1d2d9c'
down_revision = '38cbbe8bb594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pteamtagreference',
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('pteam_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pteam_id'], ['pteam.pteam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reference_id'),
    sa.UniqueConstraint('pteam_id', 'tag_id', 'group', 'target', 'version', name='pteamtagreference_pteam_id_tag_id_group_target_version_key')
    )
    op.create_index(op.f('ix_pteamtagreference_group'), 'pteamtagreference', ['group'], unique=False)
    op.create_index(op.f('ix_pteamtagreference_pteam_id'), 'pteamtagreference', ['pteam_id'], unique=False)
    op.create_index(op.f('ix_pteamtagreference_tag_id'), 'pteamtagreference', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pteamtagreference_tag_id'), table_name='pteamtagreference')
    op.drop_index(op.f('ix_pteamtagreference_pteam_id'), table_name='pteamtagreference')
    op.drop_index(op.f('ix_pteamtagreference_group'), table_name='pteamtagreference')
    op.drop_table('pteamtagreference')
    # ### end Alembic commands ###
