"""delete_disabled

Revision ID: 60ecd0090353
Revises: 373a66ea574d
Create Date: 2024-05-24 06:30:05.069193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ecd0090353'
down_revision = '373a66ea574d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pteam', 'disabled')
    op.drop_column('topic', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('pteam', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
