"""delete_disabled

Revision ID: 60ecd0090353
Revises: 373a66ea574d
Create Date: 2024-05-24 06:30:05.069193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ecd0090353'
down_revision = '373a66ea574d'
branch_labels = None
depends_on = None


def _delete_topic_disabled() -> None:
    op.get_bind().exec_driver_sql(
        "DELETE FROM topic WHERE topic.disabled = TRUE"
    )

def _delete_pteam_disabled() -> None:
    op.get_bind().exec_driver_sql(
        "DELETE FROM pteam WHERE pteam.disabled = TRUE"
    )

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actionlog_pteam_id_fkey', 'actionlog', type_='foreignkey')
    op.create_foreign_key('actionlog_pteam_id_fkey', 'actionlog', 'pteam', ['pteam_id'], ['pteam_id'], ondelete='CASCADE')
    op.drop_constraint('ateampteam_pteam_id_fkey', 'ateampteam', type_='foreignkey')
    op.create_foreign_key('ateampteam_pteam_id_fkey', 'ateampteam', 'pteam', ['pteam_id'], ['pteam_id'], ondelete='CASCADE')
    op.drop_constraint('currentpteamtopictagstatus_pteam_id_fkey', 'currentpteamtopictagstatus', type_='foreignkey')
    op.create_foreign_key('currentpteamtopictagstatus_pteam_id_fkey', 'currentpteamtopictagstatus', 'pteam', ['pteam_id'], ['pteam_id'], ondelete='CASCADE')
    op.drop_constraint('pteamaccount_pteam_id_fkey', 'pteamaccount', type_='foreignkey')
    op.create_foreign_key('pteamaccount_pteam_id_fkey', 'pteamaccount', 'pteam', ['pteam_id'], ['pteam_id'], ondelete='CASCADE')
    op.drop_constraint('pteamauthority_pteam_id_fkey', 'pteamauthority', type_='foreignkey')
    op.create_foreign_key('pteamauthority_pteam_id_fkey', 'pteamauthority', 'pteam', ['pteam_id'], ['pteam_id'], ondelete='CASCADE')
    op.drop_constraint('pteaminvitation_pteam_id_fkey', 'pteaminvitation', type_='foreignkey')
    op.create_foreign_key('pteaminvitation_pteam_id_fkey', 'pteaminvitation', 'pteam', ['pteam_id'], ['pteam_id'], ondelete='CASCADE')
    op.drop_constraint('pteamtopictagstatus_pteam_id_fkey', 'pteamtopictagstatus', type_='foreignkey')
    op.create_foreign_key('pteamtopictagstatus_pteam_id_fkey', 'pteamtopictagstatus', 'pteam', ['pteam_id'], ['pteam_id'], ondelete='CASCADE')
    _delete_pteam_disabled()
    _delete_topic_disabled()
    op.drop_column('pteam', 'disabled')
    op.drop_column('topic', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('FALSE'), autoincrement=False, nullable=False))
    op.alter_column('topic', 'disabled', server_default=None)
    op.add_column('pteam', sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('FALSE'), autoincrement=False, nullable=False))
    op.alter_column('pteam', 'disabled', server_default=None)
    op.drop_constraint('pteamtopictagstatus_pteam_id_fkey', 'pteamtopictagstatus', type_='foreignkey')
    op.create_foreign_key('pteamtopictagstatus_pteam_id_fkey', 'pteamtopictagstatus', 'pteam', ['pteam_id'], ['pteam_id'])
    op.drop_constraint('pteaminvitation_pteam_id_fkey', 'pteaminvitation', type_='foreignkey')
    op.create_foreign_key('pteaminvitation_pteam_id_fkey', 'pteaminvitation', 'pteam', ['pteam_id'], ['pteam_id'])
    op.drop_constraint('pteamauthority_pteam_id_fkey', 'pteamauthority', type_='foreignkey')
    op.create_foreign_key('pteamauthority_pteam_id_fkey', 'pteamauthority', 'pteam', ['pteam_id'], ['pteam_id'])
    op.drop_constraint('pteamaccount_pteam_id_fkey', 'pteamaccount', type_='foreignkey')
    op.create_foreign_key('pteamaccount_pteam_id_fkey', 'pteamaccount', 'pteam', ['pteam_id'], ['pteam_id'])
    op.drop_constraint('currentpteamtopictagstatus_pteam_id_fkey', 'currentpteamtopictagstatus', type_='foreignkey')
    op.create_foreign_key('currentpteamtopictagstatus_pteam_id_fkey', 'currentpteamtopictagstatus', 'pteam', ['pteam_id'], ['pteam_id'])
    op.drop_constraint('ateampteam_pteam_id_fkey', 'ateampteam', type_='foreignkey')
    op.create_foreign_key('ateampteam_pteam_id_fkey', 'ateampteam', 'pteam', ['pteam_id'], ['pteam_id'])
    op.drop_constraint('actionlog_pteam_id_fkey', 'actionlog', type_='foreignkey')
    op.create_foreign_key('actionlog_pteam_id_fkey', 'actionlog', 'pteam', ['pteam_id'], ['pteam_id'])
    # ### end Alembic commands ###
