"""obsolete ateam

Revision ID: 79208ca4528e
Revises: 3f1137b70d1a
Create Date: 2024-11-22 01:32:04.245714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79208ca4528e'
down_revision = '3f1137b70d1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ateamauthority_ateam_id', table_name='ateamauthority')
    op.drop_index('ix_ateamauthority_user_id', table_name='ateamauthority')
    op.drop_table('ateamauthority')
    op.drop_index('ix_ateammail_ateam_id', table_name='ateammail')
    op.drop_table('ateammail')
    op.drop_index('ix_ateamslack_ateam_id', table_name='ateamslack')
    op.drop_table('ateamslack')
    op.drop_index('ix_ateampteam_ateam_id', table_name='ateampteam')
    op.drop_index('ix_ateampteam_pteam_id', table_name='ateampteam')
    op.drop_table('ateampteam')
    op.drop_index('ix_ateamwatchingrequest_ateam_id', table_name='ateamwatchingrequest')
    op.drop_index('ix_ateamwatchingrequest_user_id', table_name='ateamwatchingrequest')
    op.drop_table('ateamwatchingrequest')
    op.drop_index('ix_ateamtopiccomment_ateam_id', table_name='ateamtopiccomment')
    op.drop_index('ix_ateamtopiccomment_topic_id', table_name='ateamtopiccomment')
    op.drop_index('ix_ateamtopiccomment_user_id', table_name='ateamtopiccomment')
    op.drop_table('ateamtopiccomment')
    op.drop_table('ateam')
    op.drop_index('ix_ateamaccount_ateam_id', table_name='ateamaccount')
    op.drop_index('ix_ateamaccount_user_id', table_name='ateamaccount')
    op.drop_table('ateamaccount')
    op.drop_index('ix_ateaminvitation_ateam_id', table_name='ateaminvitation')
    op.drop_index('ix_ateaminvitation_user_id', table_name='ateaminvitation')
    op.drop_table('ateaminvitation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ateaminvitation',
    sa.Column('invitation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('limit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('authority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateaminvitation_ateam_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], name='ateaminvitation_user_id_fkey'),
    sa.PrimaryKeyConstraint('invitation_id', name='ateaminvitation_pkey')
    )
    op.create_index('ix_ateaminvitation_user_id', 'ateaminvitation', ['user_id'], unique=False)
    op.create_index('ix_ateaminvitation_ateam_id', 'ateaminvitation', ['ateam_id'], unique=False)
    op.create_table('ateamaccount',
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateamaccount_ateam_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], name='ateamaccount_user_id_fkey'),
    sa.PrimaryKeyConstraint('ateam_id', 'user_id', name='ateamaccount_pkey')
    )
    op.create_index('ix_ateamaccount_user_id', 'ateamaccount', ['user_id'], unique=False)
    op.create_index('ix_ateamaccount_ateam_id', 'ateamaccount', ['ateam_id'], unique=False)
    op.create_table('ateam',
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ateam_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ateam_id', name='ateam_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ateamtopiccomment',
    sa.Column('comment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateamtopiccomment_ateam_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], name='ateamtopiccomment_topic_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], name='ateamtopiccomment_user_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', name='ateamtopiccomment_pkey')
    )
    op.create_index('ix_ateamtopiccomment_user_id', 'ateamtopiccomment', ['user_id'], unique=False)
    op.create_index('ix_ateamtopiccomment_topic_id', 'ateamtopiccomment', ['topic_id'], unique=False)
    op.create_index('ix_ateamtopiccomment_ateam_id', 'ateamtopiccomment', ['ateam_id'], unique=False)
    op.create_table('ateamwatchingrequest',
    sa.Column('request_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('limit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateamwatchingrequest_ateam_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], name='ateamwatchingrequest_user_id_fkey'),
    sa.PrimaryKeyConstraint('request_id', name='ateamwatchingrequest_pkey')
    )
    op.create_index('ix_ateamwatchingrequest_user_id', 'ateamwatchingrequest', ['user_id'], unique=False)
    op.create_index('ix_ateamwatchingrequest_ateam_id', 'ateamwatchingrequest', ['ateam_id'], unique=False)
    op.create_table('ateampteam',
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('pteam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateampteam_ateam_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pteam_id'], ['pteam.pteam_id'], name='ateampteam_pteam_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ateam_id', 'pteam_id', name='ateampteam_pkey')
    )
    op.create_index('ix_ateampteam_pteam_id', 'ateampteam', ['pteam_id'], unique=False)
    op.create_index('ix_ateampteam_ateam_id', 'ateampteam', ['ateam_id'], unique=False)
    op.create_table('ateamslack',
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('webhook_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateamslack_ateam_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ateam_id', name='ateamslack_pkey')
    )
    op.create_index('ix_ateamslack_ateam_id', 'ateamslack', ['ateam_id'], unique=False)
    op.create_table('ateammail',
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateammail_ateam_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ateam_id', name='ateammail_pkey')
    )
    op.create_index('ix_ateammail_ateam_id', 'ateammail', ['ateam_id'], unique=False)
    op.create_table('ateamauthority',
    sa.Column('ateam_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('authority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ateam_id'], ['ateam.ateam_id'], name='ateamauthority_ateam_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], name='ateamauthority_user_id_fkey'),
    sa.PrimaryKeyConstraint('ateam_id', 'user_id', name='ateamauthority_pkey')
    )
    op.create_index('ix_ateamauthority_user_id', 'ateamauthority', ['user_id'], unique=False)
    op.create_index('ix_ateamauthority_ateam_id', 'ateamauthority', ['ateam_id'], unique=False)
    # ### end Alembic commands ###
