"""add slack webhook url

Revision ID: 8df12f0653b8
Revises: 982664e26b3d
Create Date: 2024-02-27 07:53:14.490610

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.engine import Connection

# revision identifiers, used by Alembic.
revision = "8df12f0653b8"
down_revision = "982664e26b3d"
branch_labels = None
depends_on = None


def insert_pteam_slack_webhook_url(connection: Connection):
    query = (
        "INSERT INTO pteamslack (pteam_id, enable, webhook_url)"
        " SELECT pteam_id, false, slack_webhook_url FROM pteam"
    )
    connection.exec_driver_sql(query)


def insert_ateam_slack_webhook_url(connection: Connection):
    query = (
        "INSERT INTO ateamslack (ateam_id, enable, webhook_url)"
        " SELECT ateam_id, false, slack_webhook_url FROM ateam"
    )
    connection.exec_driver_sql(query)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ateamslack",
        sa.Column("ateam_id", sa.String(length=36), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["ateam_id"], ["ateam.ateam_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ateam_id"),
    )
    op.create_index(op.f("ix_ateamslack_ateam_id"), "ateamslack", ["ateam_id"], unique=False)
    op.create_table(
        "pteamslack",
        sa.Column("pteam_id", sa.String(length=36), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["pteam_id"], ["pteam.pteam_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pteam_id"),
    )
    op.create_index(op.f("ix_pteamslack_pteam_id"), "pteamslack", ["pteam_id"], unique=False)

    connection = op.get_bind()
    insert_pteam_slack_webhook_url(connection)
    insert_ateam_slack_webhook_url(connection)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pteamslack_pteam_id"), table_name="pteamslack")
    op.drop_table("pteamslack")
    op.drop_index(op.f("ix_ateamslack_ateam_id"), table_name="ateamslack")
    op.drop_table("ateamslack")
    # ### end Alembic commands ###
