"""delete hint_for_action

Revision ID: 986eb985ab25
Revises: ce8ccec8d851
Create Date: 2024-06-14 02:38:28.936405

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "986eb985ab25"
down_revision = "ce8ccec8d851"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "hint_for_action")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic", sa.Column("hint_for_action", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
