"""add service table and dependency table

Revision ID: b51315587b5d
Revises: 47fd451d5c21
Create Date: 2024-04-11 05:14:52.954202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51315587b5d'
down_revision = '47fd451d5c21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('pteam_id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pteam_id'], ['pteam.pteam_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_service_pteam_id'), 'service', ['pteam_id'], unique=False)
    op.create_table('dependency',
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'tag_id', 'version', 'target')
    )
    op.create_index(op.f('ix_dependency_service_id'), 'dependency', ['service_id'], unique=False)
    op.create_index(op.f('ix_dependency_tag_id'), 'dependency', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dependency_tag_id'), table_name='dependency')
    op.drop_index(op.f('ix_dependency_service_id'), table_name='dependency')
    op.drop_table('dependency')
    op.drop_index(op.f('ix_service_pteam_id'), table_name='service')
    op.drop_table('service')
    # ### end Alembic commands ###
