"""delete_fingerprint

Revision ID: b842fabcecf2
Revises: 9b2de9a1ff65
Create Date: 2025-04-25 00:18:48.199200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b842fabcecf2'
down_revision = '9b2de9a1ff65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vuln', 'content_fingerprint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vuln', sa.Column('content_fingerprint', sa.TEXT(), autoincrement=False, server_default="", nullable=False))
    op.alter_column("vuln", "content_fingerprint", server_default=None, nullable=False)
    # ### end Alembic commands ###
