"""change_topic_default

Revision ID: c0ce4f1cf87a
Revises: 7842ab8d58ec
Create Date: 2024-09-11 04:07:07.389459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0ce4f1cf87a'
down_revision = '7842ab8d58ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'exploitation',
               existing_type=postgresql.ENUM('ACTIVE', 'PUBLIC_POC', 'NONE', name='exploitationenum'),
               nullable=False,
               server_default=sa.text("'NONE'::exploitationenum"))
    op.alter_column('topic', 'automatable',
               existing_type=postgresql.ENUM('YES', 'NO', name='automatableenum'),
               nullable=False,
               server_default=sa.text("'NO'::automatableenum"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'automatable',
               existing_type=postgresql.ENUM('YES', 'NO', name='automatableenum'),
               nullable=False,
               server_default=sa.text("'YES'::automatableenum"))
    op.alter_column('topic', 'exploitation',
               existing_type=postgresql.ENUM('ACTIVE', 'PUBLIC_POC', 'NONE', name='exploitationenum'),
               nullable=False,
               server_default=sa.text("'ACTIVE'::exploitationenum"))
    # ### end Alembic commands ###
