"""fix account to be deletable

Revision ID: c48d64cb47b3
Revises: e23a3e347f25
Create Date: 2025-03-21 01:46:33.851926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48d64cb47b3'
down_revision = 'e23a3e347f25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actionlog_user_id_fkey', 'actionlog', type_='foreignkey')
    op.create_foreign_key(None, 'actionlog', 'account', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.drop_constraint('pteamaccountrole_user_id_fkey', 'pteamaccountrole', type_='foreignkey')
    op.create_foreign_key(None, 'pteamaccountrole', 'account', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('pteaminvitation_user_id_fkey', 'pteaminvitation', type_='foreignkey')
    op.create_foreign_key(None, 'pteaminvitation', 'account', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('ticketstatus_user_id_fkey', 'ticketstatus', type_='foreignkey')
    op.create_foreign_key(None, 'ticketstatus', 'account', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.alter_column('topic', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('topic_created_by_fkey', 'topic', type_='foreignkey')
    op.create_foreign_key(None, 'topic', 'account', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.alter_column('topicaction', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('topicaction_created_by_fkey', 'topicaction', type_='foreignkey')
    op.create_foreign_key(None, 'topicaction', 'account', ['created_by'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topicaction', type_='foreignkey')
    op.create_foreign_key('topicaction_created_by_fkey', 'topicaction', 'account', ['created_by'], ['user_id'])
    op.alter_column('topicaction', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.create_foreign_key('topic_created_by_fkey', 'topic', 'account', ['created_by'], ['user_id'])
    op.alter_column('topic', 'created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'ticketstatus', type_='foreignkey')
    op.create_foreign_key('ticketstatus_user_id_fkey', 'ticketstatus', 'account', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'pteaminvitation', type_='foreignkey')
    op.create_foreign_key('pteaminvitation_user_id_fkey', 'pteaminvitation', 'account', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'pteamaccountrole', type_='foreignkey')
    op.create_foreign_key('pteamaccountrole_user_id_fkey', 'pteamaccountrole', 'account', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'actionlog', type_='foreignkey')
    op.create_foreign_key('actionlog_user_id_fkey', 'actionlog', 'account', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
