"""‘add threat tabl

Revision ID: d8fe2e472911
Revises: b51315587b5d
Create Date: 2024-04-19 06:47:48.425897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fe2e472911'
down_revision = 'b51315587b5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat',
    sa.Column('threat_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threat_id')
    )
    op.create_index(op.f('ix_threat_service_id'), 'threat', ['service_id'], unique=False)
    op.create_index(op.f('ix_threat_tag_id'), 'threat', ['tag_id'], unique=False)
    op.create_index(op.f('ix_threat_topic_id'), 'threat', ['topic_id'], unique=False)
    op.drop_constraint('service_pteam_id_service_name_key', 'service', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('service_pteam_id_service_name_key', 'service', ['pteam_id', 'service_name'])
    op.drop_index(op.f('ix_threat_topic_id'), table_name='threat')
    op.drop_index(op.f('ix_threat_tag_id'), table_name='threat')
    op.drop_index(op.f('ix_threat_service_id'), table_name='threat')
    op.drop_table('threat')
    # ### end Alembic commands ###
