"""add_cve_id

Revision ID: f0c931f153b4
Revises: 884b692bb1e6
Create Date: 2024-12-13 06:06:58.845366

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f0c931f153b4"
down_revision = "4912bc5835e5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("topic", sa.Column("cve_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        """
    WITH cve_matches AS (
        SELECT 
            t.topic_id,
            mt.tag_name AS cve_tag
        FROM topic t
        JOIN topicmisptag tmt ON t.topic_id = tmt.topic_id
        JOIN misptag mt ON tmt.tag_id = mt.tag_id
        WHERE mt.tag_name ~ '^CVE-\\d{4}-\\d{4,}$'
    )
    UPDATE topic
    SET cve_id = cve_matches.cve_tag
    FROM cve_matches
    WHERE topic.topic_id = cve_matches.topic_id;
    """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "cve_id")
    # ### end Alembic commands ###
