"""add_ticket_status_and_threat_relation

Revision ID: f196d35697d4
Revises: 3a0582573298
Create Date: 2024-05-17 01:10:57.456438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f196d35697d4'
down_revision = '3a0582573298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticketstatus',
    sa.Column('status_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logging_ids', sa.ARRAY(sa.String(length=36)), nullable=False),
    sa.Column('assignees', sa.ARRAY(sa.String(length=36)), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_index(op.f('ix_ticketstatus_ticket_id'), 'ticketstatus', ['ticket_id'], unique=False)
    op.create_table('currentticketstatus',
    sa.Column('current_status_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('status_id', sa.String(length=36), nullable=True),
    sa.Column('threat_impact', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['ticketstatus.status_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('current_status_id')
    )
    op.create_index(op.f('ix_currentticketstatus_status_id'), 'currentticketstatus', ['status_id'], unique=False)
    op.create_index(op.f('ix_currentticketstatus_ticket_id'), 'currentticketstatus', ['ticket_id'], unique=True)
    op.add_column('currentticketstatus', sa.Column('topic_status', type_=sa.Enum(name='topicstatustype'), nullable=True))
    op.add_column('ticketstatus', sa.Column('topic_status', type_=sa.Enum(name='topicstatustype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticketstatus_ticket_id'), table_name='ticketstatus')
    op.drop_table('ticketstatus')
    op.drop_index(op.f('ix_currentticketstatus_ticket_id'), table_name='currentticketstatus')
    op.drop_index(op.f('ix_currentticketstatus_status_id'), table_name='currentticketstatus')
    op.drop_table('currentticketstatus')
    # ### end Alembic commands ###
