"""add-serviceid-to-actionlog

Revision ID: f897d415d921
Revises: 986eb985ab25
Create Date: 2024-06-17 01:18:47.027952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f897d415d921'
down_revision = '986eb985ab25'
branch_labels = None
depends_on = None

def _delete_actionlog() -> None:
    op.get_bind().exec_driver_sql(
        "DELETE FROM actionlog"
    )

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _delete_actionlog()
    op.add_column('actionlog', sa.Column('service_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_actionlog_service_id'), 'actionlog', ['service_id'], unique=False)
    op.create_foreign_key('ix_actionlog_service_id', 'actionlog', 'service', ['service_id'], ['service_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_actionlog_service_id', 'actionlog', type_='foreignkey')
    op.drop_index(op.f('ix_actionlog_service_id'), table_name='actionlog')
    op.drop_column('actionlog', 'service_id')
    # ### end Alembic commands ###
