"""safety-impact-change-reason

Revision ID: fe5f06cf70f3
Revises: 2c762d1af82e
Create Date: 2025-06-03 05:25:04.088918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5f06cf70f3'
down_revision = '2c762d1af82e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('ticket_safety_impact_change_reason', sa.Text(), nullable=True))
    op.drop_column('ticket', 'reason_safety_impact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('reason_safety_impact', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('ticket', 'ticket_safety_impact_change_reason')
    # ### end Alembic commands ###
