// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActionLogRequest
 */
export type ActionLogRequest = {
    /**
     * Action
     */
    action: string;
    /**
     * Vuln Id
     */
    vuln_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Service Id
     */
    service_id: string;
    /**
     * Ticket Id
     */
    ticket_id: string;
    /**
     * Executed At
     */
    executed_at?: string | null;
};

/**
 * ActionLogResponse
 */
export type ActionLogResponse = {
    /**
     * Logging Id
     */
    logging_id: string;
    /**
     * Vuln Id
     */
    vuln_id: string;
    /**
     * Action
     */
    action: string;
    /**
     * User Id
     */
    user_id?: string | null;
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Service Id
     */
    service_id: string;
    /**
     * Ticket Id
     */
    ticket_id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Executed At
     */
    executed_at: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * AffectedObject
 */
export type AffectedObject = {
    object_category: ObjectCategoryEnum;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * ApplyInvitationRequest
 */
export type ApplyInvitationRequest = {
    /**
     * Invitation Id
     */
    invitation_id: string;
};

/**
 * AutomatableEnum
 */
export type AutomatableEnum = 'yes' | 'no';

/**
 * Body_login_for_access_token_auth_token_post
 */
export type BodyLoginForAccessTokenAuthTokenPost = {
    /**
     * Username
     */
    username: string;
};

/**
 * Body_upload_pteam_packages_file_pteams__pteam_id__upload_packages_file_post
 */
export type BodyUploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_pteam_sbom_file_pteams__pteam_id__upload_sbom_file_post
 */
export type BodyUploadPteamSbomFilePteamsPteamIdUploadSbomFilePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_service_thumbnail_pteams__pteam_id__services__service_id__thumbnail_post
 */
export type BodyUploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPost = {
    /**
     * Uploaded
     */
    uploaded: Blob | File;
};

/**
 * DependencyResponse
 */
export type DependencyResponse = {
    /**
     * Dependency Id
     */
    dependency_id: string;
    /**
     * Service Id
     */
    service_id: string;
    /**
     * Package Version Id
     */
    package_version_id: string;
    /**
     * Package Id
     */
    package_id: string;
    /**
     * Package Manager
     */
    package_manager: string;
    /**
     * Target
     */
    target: string;
    /**
     * Dependency Mission Impact
     */
    dependency_mission_impact?: string | null;
    /**
     * Package Name
     */
    package_name: string;
    /**
     * Package Source Name
     */
    package_source_name?: string | null;
    /**
     * Package Version
     */
    package_version: string;
    /**
     * Package Ecosystem
     */
    package_ecosystem: string;
    /**
     * Vuln Matching Ecosystem
     */
    vuln_matching_ecosystem: string;
};

/**
 * EmailCheckRequest
 */
export type EmailCheckRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * EoLProductListResponse
 */
export type EoLProductListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Products
     */
    products: Array<EoLProductResponse>;
};

/**
 * EoLProductResponse
 */
export type EoLProductResponse = {
    /**
     * Eol Product Id
     */
    eol_product_id: string;
    /**
     * Name
     */
    name: string;
    product_category: ProductCategoryEnum;
    /**
     * Description
     */
    description: string | null;
    /**
     * Is Ecosystem
     */
    is_ecosystem: boolean;
    /**
     * Matching Name
     */
    matching_name: string;
    /**
     * Eol Versions
     */
    eol_versions?: Array<EoLVersionResponse>;
};

/**
 * EoLVersionResponse
 */
export type EoLVersionResponse = {
    /**
     * Eol Version Id
     */
    eol_version_id: string;
    /**
     * Version
     */
    version: string;
    /**
     * Release Date
     */
    release_date: string | null;
    /**
     * Eol From
     */
    eol_from: string;
    /**
     * Matching Version
     */
    matching_version: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ExploitationEnum
 */
export type ExploitationEnum = 'active' | 'public_poc' | 'none';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImpactCategoryEnum
 */
export type ImpactCategoryEnum = 'damage_to_property' | 'denial_of_control' | 'denial_of_view' | 'loss_of_availability' | 'loss_of_control' | 'loss_of_productivity_and_revenue' | 'loss_of_protection' | 'loss_of_safety' | 'loss_of_view' | 'manipulation_of_control' | 'manipulation_of_view' | 'theft_of_operational_information';

/**
 * InsightReference
 */
export type InsightReference = {
    /**
     * Link Text
     */
    link_text: string;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * InsightResponse
 */
export type InsightResponse = {
    /**
     * Description
     */
    description: string;
    /**
     * Data Processing Strategy
     */
    data_processing_strategy: string;
    /**
     * Threat Scenarios
     */
    threat_scenarios?: Array<ThreatScenario>;
    /**
     * Affected Objects
     */
    affected_objects?: Array<AffectedObject>;
    /**
     * Insight References
     */
    insight_references?: Array<InsightReference>;
    /**
     * Ticket Id
     */
    ticket_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * InsightUpdateRequest
 */
export type InsightUpdateRequest = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Data Processing Strategy
     */
    data_processing_strategy?: string | null;
    /**
     * Threat Scenarios
     */
    threat_scenarios?: Array<ThreatScenario> | null;
    /**
     * Affected Objects
     */
    affected_objects?: Array<AffectedObject> | null;
    /**
     * Insight References
     */
    insight_references?: Array<InsightReference> | null;
};

/**
 * Mail
 */
export type Mail = {
    /**
     * Enable
     */
    enable: boolean;
    /**
     * Address
     */
    address: string;
};

/**
 * MissionImpactEnum
 */
export type MissionImpactEnum = 'mission_failure' | 'mef_failure' | 'mef_support_crippled' | 'degraded';

/**
 * ObjectCategoryEnum
 */
export type ObjectCategoryEnum = 'server' | 'client_device' | 'mobile_device' | 'network_device' | 'storage' | 'iot_device' | 'physical_media' | 'facility' | 'person';

/**
 * PTeamCreateRequest
 */
export type PTeamCreateRequest = {
    /**
     * Pteam Name
     */
    pteam_name: string;
    /**
     * Contact Info
     */
    contact_info?: string;
    alert_slack?: Slack | null;
    alert_ssvc_priority?: SsvcDeployerPriorityEnum;
    alert_mail?: Mail | null;
};

/**
 * PTeamEntry
 */
export type PTeamEntry = {
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Pteam Name
     */
    pteam_name: string;
    /**
     * Contact Info
     */
    contact_info: string;
};

/**
 * PTeamInfo
 */
export type PTeamInfo = {
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Pteam Name
     */
    pteam_name: string;
    /**
     * Contact Info
     */
    contact_info: string;
    alert_slack: Slack;
    alert_ssvc_priority: SsvcDeployerPriorityEnum;
    /**
     * Services
     */
    services: Array<PTeamServiceResponse>;
    alert_mail: Mail;
};

/**
 * PTeamInvitationRequest
 */
export type PTeamInvitationRequest = {
    /**
     * Expiration
     */
    expiration: string;
    /**
     * Limit Count
     */
    limit_count?: number | null;
};

/**
 * PTeamInvitationResponse
 */
export type PTeamInvitationResponse = {
    /**
     * Invitation Id
     */
    invitation_id: string;
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Expiration
     */
    expiration: string;
    /**
     * Limit Count
     */
    limit_count?: number | null;
    /**
     * Used Count
     */
    used_count: number;
};

/**
 * PTeamInviterResponse
 */
export type PTeamInviterResponse = {
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Pteam Name
     */
    pteam_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * PTeamMemberUpdateRequest
 */
export type PTeamMemberUpdateRequest = {
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * PTeamMemberUpdateResponse
 */
export type PTeamMemberUpdateResponse = {
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * PTeamPackageSummary
 */
export type PTeamPackageSummary = {
    /**
     * Package Id
     */
    package_id: string;
    /**
     * Package Name
     */
    package_name: string;
    /**
     * Ecosystem
     */
    ecosystem: string;
    /**
     * Package Managers
     */
    package_managers: Array<string>;
    /**
     * Service Ids
     */
    service_ids: Array<string>;
    ssvc_priority: SsvcDeployerPriorityEnum | null;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Status Count
     */
    status_count: {
        [key: string]: number;
    };
};

/**
 * PTeamPackagesSummary
 */
export type PTeamPackagesSummary = {
    /**
     * Ssvc Priority Count
     */
    ssvc_priority_count: {
        [key in SsvcDeployerPriorityEnum]?: number;
    };
    /**
     * Packages
     */
    packages: Array<PTeamPackageSummary>;
};

/**
 * PTeamRole
 */
export type PTeamRole = {
    /**
     * Is Admin
     */
    is_admin: boolean;
    pteam: PTeamEntry;
};

/**
 * PTeamServiceResponse
 */
export type PTeamServiceResponse = {
    /**
     * Service Name
     */
    service_name: string;
    /**
     * Service Id
     */
    service_id: string;
    /**
     * Sbom Uploaded At
     */
    sbom_uploaded_at?: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Keywords
     */
    keywords: Array<string>;
    system_exposure: SystemExposureEnum;
    service_mission_impact: MissionImpactEnum;
    service_safety_impact: SafetyImpactEnum;
};

/**
 * PTeamServiceUpdateRequest
 */
export type PTeamServiceUpdateRequest = {
    /**
     * Service Name
     */
    service_name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Keywords
     */
    keywords?: Array<string> | null;
    system_exposure?: SystemExposureEnum | null;
    service_mission_impact?: MissionImpactEnum | null;
    service_safety_impact?: SafetyImpactEnum | null;
};

/**
 * PTeamServiceUpdateResponse
 */
export type PTeamServiceUpdateResponse = {
    /**
     * Service Name
     */
    service_name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Keywords
     */
    keywords: Array<string>;
    system_exposure: SystemExposureEnum | null;
    service_mission_impact: MissionImpactEnum | null;
    service_safety_impact: SafetyImpactEnum | null;
};

/**
 * PTeamUpdateRequest
 */
export type PTeamUpdateRequest = {
    /**
     * Pteam Name
     */
    pteam_name?: string | null;
    /**
     * Contact Info
     */
    contact_info?: string | null;
    alert_slack?: Slack | null;
    alert_ssvc_priority?: SsvcDeployerPriorityEnum | null;
    alert_mail?: Mail | null;
};

/**
 * PackageFileResponse
 */
export type PackageFileResponse = {
    /**
     * Package Id
     */
    package_id: string;
    /**
     * Package Name
     */
    package_name: string;
    /**
     * Ecosystem
     */
    ecosystem: string;
    /**
     * References
     */
    references?: Array<Reference>;
};

/**
 * ProductCategoryEnum
 */
export type ProductCategoryEnum = 'os' | 'runtime' | 'middleware' | 'package';

/**
 * PteamMemberGetResponse
 */
export type PteamMemberGetResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Uid
     */
    uid: string;
    /**
     * Email
     */
    email: string;
    /**
     * Disabled
     */
    disabled: boolean;
    /**
     * Years
     */
    years: number;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * Reference
 */
export type Reference = {
    /**
     * Service
     */
    service: string;
    /**
     * Target
     */
    target: string;
    /**
     * Package Manager
     */
    package_manager: string;
    /**
     * Version
     */
    version: string;
};

/**
 * RefreshTokenRequest
 */
export type RefreshTokenRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RelatedTicketStatus
 */
export type RelatedTicketStatus = 'solved' | 'unsolved';

/**
 * SSVCDeployerPriorityEnum
 */
export type SsvcDeployerPriorityEnum = 'immediate' | 'out_of_cycle' | 'scheduled' | 'defer';

/**
 * SafetyImpactEnum
 */
export type SafetyImpactEnum = 'catastrophic' | 'critical' | 'marginal' | 'negligible';

/**
 * ServicePackageTicketCountsSolvedUnsolved
 */
export type ServicePackageTicketCountsSolvedUnsolved = {
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Service Id
     */
    service_id: string | null;
    /**
     * Package Id
     */
    package_id: string | null;
    related_ticket_status: RelatedTicketStatus | null;
    /**
     * Ssvc Priority Count
     */
    ssvc_priority_count: {
        [key: string]: number;
    };
};

/**
 * ServicePackageVulnsSolvedUnsolved
 */
export type ServicePackageVulnsSolvedUnsolved = {
    /**
     * Pteam Id
     */
    pteam_id: string;
    /**
     * Service Id
     */
    service_id: string | null;
    /**
     * Package Id
     */
    package_id: string | null;
    related_ticket_status: RelatedTicketStatus | null;
    /**
     * Vuln Ids
     */
    vuln_ids: Array<string>;
};

/**
 * Slack
 */
export type Slack = {
    /**
     * Enable
     */
    enable: boolean;
    /**
     * Webhook Url
     */
    webhook_url: string;
};

/**
 * SlackCheckRequest
 */
export type SlackCheckRequest = {
    /**
     * Slack Webhook Url
     */
    slack_webhook_url: string;
};

/**
 * SystemExposureEnum
 */
export type SystemExposureEnum = 'open' | 'controlled' | 'small';

/**
 * ThreatScenario
 */
export type ThreatScenario = {
    impact_category: ImpactCategoryEnum;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
};

/**
 * TicketHandlingStatusType
 */
export type TicketHandlingStatusType = 'alerted' | 'acknowledged' | 'scheduled' | 'completed';

/**
 * TicketListResponse
 */
export type TicketListResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Tickets
     */
    tickets: Array<TicketResponse>;
};

/**
 * TicketResponse
 */
export type TicketResponse = {
    /**
     * Ticket Id
     */
    ticket_id: string;
    /**
     * Vuln Id
     */
    vuln_id: string;
    /**
     * Dependency Id
     */
    dependency_id: string;
    /**
     * Service Id
     */
    service_id: string;
    /**
     * Pteam Id
     */
    pteam_id: string;
    ssvc_deployer_priority: SsvcDeployerPriorityEnum | null;
    ticket_safety_impact: SafetyImpactEnum | null;
    /**
     * Ticket Safety Impact Change Reason
     */
    ticket_safety_impact_change_reason: string | null;
    ticket_status: TicketStatusResponse;
};

/**
 * TicketStatusRequest
 */
export type TicketStatusRequest = {
    ticket_handling_status?: TicketHandlingStatusType | null;
    /**
     * Logging Ids
     */
    logging_ids?: Array<string> | null;
    /**
     * Assignees
     */
    assignees?: Array<string> | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Scheduled At
     */
    scheduled_at?: string | null;
};

/**
 * TicketStatusResponse
 */
export type TicketStatusResponse = {
    /**
     * Status Id
     */
    status_id: string;
    ticket_handling_status: TicketHandlingStatusType;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Assignees
     */
    assignees?: Array<string>;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Scheduled At
     */
    scheduled_at?: string | null;
    /**
     * Action Logs
     */
    action_logs?: Array<ActionLogResponse>;
};

/**
 * TicketUpdateRequest
 */
export type TicketUpdateRequest = {
    ticket_safety_impact?: SafetyImpactEnum | null;
    /**
     * Ticket Safety Impact Change Reason
     */
    ticket_safety_impact_change_reason?: string | null;
    ticket_status?: TicketStatusRequest | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * UserCreateRequest
 */
export type UserCreateRequest = {
    /**
     * Years
     */
    years?: number;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Uid
     */
    uid: string;
    /**
     * Email
     */
    email: string;
    /**
     * Disabled
     */
    disabled: boolean;
    /**
     * Years
     */
    years: number;
    /**
     * Pteam Roles
     */
    pteam_roles: Array<PTeamRole>;
    /**
     * Default Pteam Id
     */
    default_pteam_id: string | null;
};

/**
 * UserUpdateRequest
 */
export type UserUpdateRequest = {
    /**
     * Disabled
     */
    disabled?: boolean | null;
    /**
     * Years
     */
    years?: number | null;
    /**
     * Default Pteam Id
     */
    default_pteam_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VulnResponse
 */
export type VulnResponse = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Cve Id
     */
    cve_id?: string | null;
    /**
     * Detail
     */
    detail?: string | null;
    exploitation?: ExploitationEnum | null;
    automatable?: AutomatableEnum | null;
    /**
     * Cvss V3 Score
     */
    cvss_v3_score?: number | null;
    /**
     * Vulnerable Packages
     */
    vulnerable_packages?: Array<VulnerablePackageResponse>;
    /**
     * Vuln Id
     */
    vuln_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Created By
     */
    created_by?: string | null;
};

/**
 * VulnerablePackageResponse
 */
export type VulnerablePackageResponse = {
    /**
     * Affected Name
     */
    affected_name: string;
    /**
     * Ecosystem
     */
    ecosystem: string;
    /**
     * Affected Versions
     */
    affected_versions: Array<string>;
    /**
     * Fixed Versions
     */
    fixed_versions: Array<string>;
};

/**
 * VulnsListResponse
 */
export type VulnsListResponse = {
    /**
     * Num Vulns
     */
    num_vulns: number;
    /**
     * Vulns
     */
    vulns: Array<VulnResponse>;
};

/**
 * EoLProductRequest
 */
export type EoLProductRequest = {
    /**
     * Name
     */
    name?: string | null;
    product_category?: ProductCategoryEnum | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Ecosystem
     */
    is_ecosystem?: boolean | null;
    /**
     * Matching Name
     */
    matching_name?: string | null;
    /**
     * Eol Versions
     */
    eol_versions?: Array<EoLVersionRequest>;
};

/**
 * EoLVersionRequest
 */
export type EoLVersionRequest = {
    /**
     * Version
     */
    version: string;
    /**
     * Release Date
     */
    release_date: string;
    /**
     * Eol From
     */
    eol_from: string;
    /**
     * Matching Version
     */
    matching_version: string;
};

/**
 * VulnUpdateRequest
 */
export type VulnUpdateRequest = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Cve Id
     */
    cve_id?: string | null;
    /**
     * Detail
     */
    detail?: string | null;
    exploitation?: ExploitationEnum | null;
    automatable?: AutomatableEnum | null;
    /**
     * Cvss V3 Score
     */
    cvss_v3_score?: number | null;
    /**
     * Vulnerable Packages
     */
    vulnerable_packages?: Array<VulnerablePackageResponse>;
};

/**
 * Body_login_for_access_token_auth_token_post
 */
export type BodyLoginForAccessTokenAuthTokenPostWritable = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

export type LoginForAccessTokenAuthTokenPostData = {
    body: BodyLoginForAccessTokenAuthTokenPostWritable;
    path?: never;
    query?: never;
    url: '/auth/token';
};

export type LoginForAccessTokenAuthTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenAuthTokenPostError = LoginForAccessTokenAuthTokenPostErrors[keyof LoginForAccessTokenAuthTokenPostErrors];

export type LoginForAccessTokenAuthTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginForAccessTokenAuthTokenPostResponse = LoginForAccessTokenAuthTokenPostResponses[keyof LoginForAccessTokenAuthTokenPostResponses];

export type RefreshAccessTokenAuthRefreshPostData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshAccessTokenAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshAccessTokenAuthRefreshPostError = RefreshAccessTokenAuthRefreshPostErrors[keyof RefreshAccessTokenAuthRefreshPostErrors];

export type RefreshAccessTokenAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type RefreshAccessTokenAuthRefreshPostResponse = RefreshAccessTokenAuthRefreshPostResponses[keyof RefreshAccessTokenAuthRefreshPostResponses];

export type GetLogsActionlogsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/actionlogs';
};

export type GetLogsActionlogsGetResponses = {
    /**
     * Response Get Logs Actionlogs Get
     *
     * Successful Response
     */
    200: Array<ActionLogResponse>;
};

export type GetLogsActionlogsGetResponse = GetLogsActionlogsGetResponses[keyof GetLogsActionlogsGetResponses];

export type CreateLogActionlogsPostData = {
    body: ActionLogRequest;
    path?: never;
    query?: never;
    url: '/actionlogs';
};

export type CreateLogActionlogsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLogActionlogsPostError = CreateLogActionlogsPostErrors[keyof CreateLogActionlogsPostErrors];

export type CreateLogActionlogsPostResponses = {
    /**
     * Successful Response
     */
    200: ActionLogResponse;
};

export type CreateLogActionlogsPostResponse = CreateLogActionlogsPostResponses[keyof CreateLogActionlogsPostResponses];

export type GetVulnLogsActionlogsVulnsVulnIdGetData = {
    body?: never;
    path: {
        /**
         * Vuln Id
         */
        vuln_id: string;
    };
    query?: never;
    url: '/actionlogs/vulns/{vuln_id}';
};

export type GetVulnLogsActionlogsVulnsVulnIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVulnLogsActionlogsVulnsVulnIdGetError = GetVulnLogsActionlogsVulnsVulnIdGetErrors[keyof GetVulnLogsActionlogsVulnsVulnIdGetErrors];

export type GetVulnLogsActionlogsVulnsVulnIdGetResponses = {
    /**
     * Response Get Vuln Logs Actionlogs Vulns  Vuln Id  Get
     *
     * Successful Response
     */
    200: Array<ActionLogResponse>;
};

export type GetVulnLogsActionlogsVulnsVulnIdGetResponse = GetVulnLogsActionlogsVulnsVulnIdGetResponses[keyof GetVulnLogsActionlogsVulnsVulnIdGetResponses];

export type CheckWebhookUrlExternalSlackCheckPostData = {
    body: SlackCheckRequest;
    path?: never;
    query?: never;
    url: '/external/slack/check';
};

export type CheckWebhookUrlExternalSlackCheckPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckWebhookUrlExternalSlackCheckPostError = CheckWebhookUrlExternalSlackCheckPostErrors[keyof CheckWebhookUrlExternalSlackCheckPostErrors];

export type CheckWebhookUrlExternalSlackCheckPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CheckEmailExternalEmailCheckPostData = {
    body: EmailCheckRequest;
    path?: never;
    query?: never;
    url: '/external/email/check';
};

export type CheckEmailExternalEmailCheckPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckEmailExternalEmailCheckPostError = CheckEmailExternalEmailCheckPostErrors[keyof CheckEmailExternalEmailCheckPostErrors];

export type CheckEmailExternalEmailCheckPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApplyInvitationPteamsApplyInvitationPostData = {
    body: ApplyInvitationRequest;
    path?: never;
    query?: never;
    url: '/pteams/apply_invitation';
};

export type ApplyInvitationPteamsApplyInvitationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplyInvitationPteamsApplyInvitationPostError = ApplyInvitationPteamsApplyInvitationPostErrors[keyof ApplyInvitationPteamsApplyInvitationPostErrors];

export type ApplyInvitationPteamsApplyInvitationPostResponses = {
    /**
     * Successful Response
     */
    200: PTeamInfo;
};

export type ApplyInvitationPteamsApplyInvitationPostResponse = ApplyInvitationPteamsApplyInvitationPostResponses[keyof ApplyInvitationPteamsApplyInvitationPostResponses];

export type InvitedPteamPteamsInvitationInvitationIdGetData = {
    body?: never;
    path: {
        /**
         * Invitation Id
         */
        invitation_id: string;
    };
    query?: never;
    url: '/pteams/invitation/{invitation_id}';
};

export type InvitedPteamPteamsInvitationInvitationIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InvitedPteamPteamsInvitationInvitationIdGetError = InvitedPteamPteamsInvitationInvitationIdGetErrors[keyof InvitedPteamPteamsInvitationInvitationIdGetErrors];

export type InvitedPteamPteamsInvitationInvitationIdGetResponses = {
    /**
     * Successful Response
     */
    200: PTeamInviterResponse;
};

export type InvitedPteamPteamsInvitationInvitationIdGetResponse = InvitedPteamPteamsInvitationInvitationIdGetResponses[keyof InvitedPteamPteamsInvitationInvitationIdGetResponses];

export type DeletePteamPteamsPteamIdDeleteData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}';
};

export type DeletePteamPteamsPteamIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePteamPteamsPteamIdDeleteError = DeletePteamPteamsPteamIdDeleteErrors[keyof DeletePteamPteamsPteamIdDeleteErrors];

export type DeletePteamPteamsPteamIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePteamPteamsPteamIdDeleteResponse = DeletePteamPteamsPteamIdDeleteResponses[keyof DeletePteamPteamsPteamIdDeleteResponses];

export type GetPteamPteamsPteamIdGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}';
};

export type GetPteamPteamsPteamIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPteamPteamsPteamIdGetError = GetPteamPteamsPteamIdGetErrors[keyof GetPteamPteamsPteamIdGetErrors];

export type GetPteamPteamsPteamIdGetResponses = {
    /**
     * Successful Response
     */
    200: PTeamInfo;
};

export type GetPteamPteamsPteamIdGetResponse = GetPteamPteamsPteamIdGetResponses[keyof GetPteamPteamsPteamIdGetResponses];

export type UpdatePteamPteamsPteamIdPutData = {
    body: PTeamUpdateRequest;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}';
};

export type UpdatePteamPteamsPteamIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePteamPteamsPteamIdPutError = UpdatePteamPteamsPteamIdPutErrors[keyof UpdatePteamPteamsPteamIdPutErrors];

export type UpdatePteamPteamsPteamIdPutResponses = {
    /**
     * Successful Response
     */
    200: PTeamInfo;
};

export type UpdatePteamPteamsPteamIdPutResponse = UpdatePteamPteamsPteamIdPutResponses[keyof UpdatePteamPteamsPteamIdPutResponses];

export type ForceCalculateSsvcPriorityPteamsPteamIdFixSsvcPrioritiesPostData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/fix_ssvc_priorities';
};

export type ForceCalculateSsvcPriorityPteamsPteamIdFixSsvcPrioritiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForceCalculateSsvcPriorityPteamsPteamIdFixSsvcPrioritiesPostError = ForceCalculateSsvcPriorityPteamsPteamIdFixSsvcPrioritiesPostErrors[keyof ForceCalculateSsvcPriorityPteamsPteamIdFixSsvcPrioritiesPostErrors];

export type ForceCalculateSsvcPriorityPteamsPteamIdFixSsvcPrioritiesPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPteamServicesPteamsPteamIdServicesGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/services';
};

export type GetPteamServicesPteamsPteamIdServicesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPteamServicesPteamsPteamIdServicesGetError = GetPteamServicesPteamsPteamIdServicesGetErrors[keyof GetPteamServicesPteamsPteamIdServicesGetErrors];

export type GetPteamServicesPteamsPteamIdServicesGetResponses = {
    /**
     * Response Get Pteam Services Pteams  Pteam Id  Services Get
     *
     * Successful Response
     */
    200: Array<PTeamServiceResponse>;
};

export type GetPteamServicesPteamsPteamIdServicesGetResponse = GetPteamServicesPteamsPteamIdServicesGetResponses[keyof GetPteamServicesPteamsPteamIdServicesGetResponses];

export type RemoveServicePteamsPteamIdServicesServiceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Service Id
         */
        service_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/services/{service_id}';
};

export type RemoveServicePteamsPteamIdServicesServiceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveServicePteamsPteamIdServicesServiceIdDeleteError = RemoveServicePteamsPteamIdServicesServiceIdDeleteErrors[keyof RemoveServicePteamsPteamIdServicesServiceIdDeleteErrors];

export type RemoveServicePteamsPteamIdServicesServiceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveServicePteamsPteamIdServicesServiceIdDeleteResponse = RemoveServicePteamsPteamIdServicesServiceIdDeleteResponses[keyof RemoveServicePteamsPteamIdServicesServiceIdDeleteResponses];

export type UpdatePteamServicePteamsPteamIdServicesServiceIdPutData = {
    body: PTeamServiceUpdateRequest;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Service Id
         */
        service_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/services/{service_id}';
};

export type UpdatePteamServicePteamsPteamIdServicesServiceIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePteamServicePteamsPteamIdServicesServiceIdPutError = UpdatePteamServicePteamsPteamIdServicesServiceIdPutErrors[keyof UpdatePteamServicePteamsPteamIdServicesServiceIdPutErrors];

export type UpdatePteamServicePteamsPteamIdServicesServiceIdPutResponses = {
    /**
     * Successful Response
     */
    200: PTeamServiceUpdateResponse;
};

export type UpdatePteamServicePteamsPteamIdServicesServiceIdPutResponse = UpdatePteamServicePteamsPteamIdServicesServiceIdPutResponses[keyof UpdatePteamServicePteamsPteamIdServicesServiceIdPutResponses];

export type RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Service Id
         */
        service_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/services/{service_id}/thumbnail';
};

export type RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteError = RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteErrors[keyof RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteErrors];

export type RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteResponse = RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteResponses[keyof RemoveServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailDeleteResponses];

export type GetServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Service Id
         */
        service_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/services/{service_id}/thumbnail';
};

export type GetServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailGetError = GetServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailGetErrors[keyof GetServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailGetErrors];

export type GetServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPostData = {
    body: BodyUploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPost;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Service Id
         */
        service_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/services/{service_id}/thumbnail';
};

export type UploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPostError = UploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPostErrors[keyof UploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPostErrors];

export type UploadServiceThumbnailPteamsPteamIdServicesServiceIdThumbnailPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: {
        /**
         * Service Id
         */
        service_id?: string | null;
    };
    url: '/pteams/{pteam_id}/packages/summary';
};

export type GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetError = GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetErrors[keyof GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetErrors];

export type GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetResponses = {
    /**
     * Successful Response
     */
    200: PTeamPackagesSummary;
};

export type GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetResponse = GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetResponses[keyof GetPteamPackagesSummaryPteamsPteamIdPackagesSummaryGetResponses];

export type GetDependenciesPteamsPteamIdDependenciesGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Service Id
         */
        service_id?: string | null;
        /**
         * Package Id
         */
        package_id?: string | null;
    };
    url: '/pteams/{pteam_id}/dependencies';
};

export type GetDependenciesPteamsPteamIdDependenciesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDependenciesPteamsPteamIdDependenciesGetError = GetDependenciesPteamsPteamIdDependenciesGetErrors[keyof GetDependenciesPteamsPteamIdDependenciesGetErrors];

export type GetDependenciesPteamsPteamIdDependenciesGetResponses = {
    /**
     * Response Get Dependencies Pteams  Pteam Id  Dependencies Get
     *
     * Successful Response
     */
    200: Array<DependencyResponse>;
};

export type GetDependenciesPteamsPteamIdDependenciesGetResponse = GetDependenciesPteamsPteamIdDependenciesGetResponses[keyof GetDependenciesPteamsPteamIdDependenciesGetResponses];

export type GetDependencyPteamsPteamIdDependenciesDependencyIdGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Dependency Id
         */
        dependency_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/dependencies/{dependency_id}';
};

export type GetDependencyPteamsPteamIdDependenciesDependencyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDependencyPteamsPteamIdDependenciesDependencyIdGetError = GetDependencyPteamsPteamIdDependenciesDependencyIdGetErrors[keyof GetDependencyPteamsPteamIdDependenciesDependencyIdGetErrors];

export type GetDependencyPteamsPteamIdDependenciesDependencyIdGetResponses = {
    /**
     * Successful Response
     */
    200: DependencyResponse;
};

export type GetDependencyPteamsPteamIdDependenciesDependencyIdGetResponse = GetDependencyPteamsPteamIdDependenciesDependencyIdGetResponses[keyof GetDependencyPteamsPteamIdDependenciesDependencyIdGetResponses];

export type GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: {
        /**
         * Service Id
         */
        service_id?: string | null;
        /**
         * Package Id
         */
        package_id?: string | null;
        /**
         * Related Ticket Status
         */
        related_ticket_status?: RelatedTicketStatus | null;
    };
    url: '/pteams/{pteam_id}/vuln_ids';
};

export type GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetError = GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetErrors[keyof GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetErrors];

export type GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetResponses = {
    /**
     * Successful Response
     */
    200: ServicePackageVulnsSolvedUnsolved;
};

export type GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetResponse = GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetResponses[keyof GetVulnIdsTiedToServicePackagePteamsPteamIdVulnIdsGetResponses];

export type GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: {
        /**
         * Service Id
         */
        service_id?: string | null;
        /**
         * Package Id
         */
        package_id?: string | null;
        /**
         * Related Ticket Status
         */
        related_ticket_status?: RelatedTicketStatus | null;
    };
    url: '/pteams/{pteam_id}/ticket_counts';
};

export type GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetError = GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetErrors[keyof GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetErrors];

export type GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetResponses = {
    /**
     * Successful Response
     */
    200: ServicePackageTicketCountsSolvedUnsolved;
};

export type GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetResponse = GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetResponses[keyof GetTicketCountsTiedToServicePackagePteamsPteamIdTicketCountsGetResponses];

export type GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: {
        /**
         * Service Id
         */
        service_id?: string | null;
        /**
         * Package Id
         */
        package_id?: string | null;
        /**
         * Vuln Id
         */
        vuln_id?: string | null;
        /**
         * Assigned To Me
         */
        assigned_to_me?: boolean;
    };
    url: '/pteams/{pteam_id}/tickets';
};

export type GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetError = GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetErrors[keyof GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetErrors];

export type GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetResponses = {
    /**
     * Response Get Tickets By Service Id And Package Id And Vuln Id Pteams  Pteam Id  Tickets Get
     *
     * Successful Response
     */
    200: Array<TicketResponse>;
};

export type GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetResponse = GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetResponses[keyof GetTicketsByServiceIdAndPackageIdAndVulnIdPteamsPteamIdTicketsGetResponses];

export type GetTicketPteamsPteamIdTicketsTicketIdGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/tickets/{ticket_id}';
};

export type GetTicketPteamsPteamIdTicketsTicketIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketPteamsPteamIdTicketsTicketIdGetError = GetTicketPteamsPteamIdTicketsTicketIdGetErrors[keyof GetTicketPteamsPteamIdTicketsTicketIdGetErrors];

export type GetTicketPteamsPteamIdTicketsTicketIdGetResponses = {
    /**
     * Successful Response
     */
    200: TicketResponse;
};

export type GetTicketPteamsPteamIdTicketsTicketIdGetResponse = GetTicketPteamsPteamIdTicketsTicketIdGetResponses[keyof GetTicketPteamsPteamIdTicketsTicketIdGetResponses];

export type UpdateTicketPteamsPteamIdTicketsTicketIdPutData = {
    body: TicketUpdateRequest;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/tickets/{ticket_id}';
};

export type UpdateTicketPteamsPteamIdTicketsTicketIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTicketPteamsPteamIdTicketsTicketIdPutError = UpdateTicketPteamsPteamIdTicketsTicketIdPutErrors[keyof UpdateTicketPteamsPteamIdTicketsTicketIdPutErrors];

export type UpdateTicketPteamsPteamIdTicketsTicketIdPutResponses = {
    /**
     * Successful Response
     */
    200: TicketResponse;
};

export type UpdateTicketPteamsPteamIdTicketsTicketIdPutResponse = UpdateTicketPteamsPteamIdTicketsTicketIdPutResponses[keyof UpdateTicketPteamsPteamIdTicketsTicketIdPutResponses];

export type CreatePteamPteamsPostData = {
    body: PTeamCreateRequest;
    path?: never;
    query?: never;
    url: '/pteams';
};

export type CreatePteamPteamsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePteamPteamsPostError = CreatePteamPteamsPostErrors[keyof CreatePteamPteamsPostErrors];

export type CreatePteamPteamsPostResponses = {
    /**
     * Successful Response
     */
    200: PTeamInfo;
};

export type CreatePteamPteamsPostResponse = CreatePteamPteamsPostResponses[keyof CreatePteamPteamsPostResponses];

export type UploadPteamSbomFilePteamsPteamIdUploadSbomFilePostData = {
    body: BodyUploadPteamSbomFilePteamsPteamIdUploadSbomFilePost;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: {
        /**
         * Service
         *
         * name of service(repository or product)
         */
        service?: string;
    };
    url: '/pteams/{pteam_id}/upload_sbom_file';
};

export type UploadPteamSbomFilePteamsPteamIdUploadSbomFilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadPteamSbomFilePteamsPteamIdUploadSbomFilePostError = UploadPteamSbomFilePteamsPteamIdUploadSbomFilePostErrors[keyof UploadPteamSbomFilePteamsPteamIdUploadSbomFilePostErrors];

export type UploadPteamSbomFilePteamsPteamIdUploadSbomFilePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostData = {
    body: BodyUploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePost;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: {
        /**
         * Service
         *
         * name of service(repository or product)
         */
        service?: string;
    };
    url: '/pteams/{pteam_id}/upload_packages_file';
};

export type UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostError = UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostErrors[keyof UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostErrors];

export type UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostResponses = {
    /**
     * Response Upload Pteam Packages File Pteams  Pteam Id  Upload Packages File Post
     *
     * Successful Response
     */
    200: Array<PackageFileResponse>;
};

export type UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostResponse = UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostResponses[keyof UploadPteamPackagesFilePteamsPteamIdUploadPackagesFilePostResponses];

export type GetPteamMembersPteamsPteamIdMembersGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/members';
};

export type GetPteamMembersPteamsPteamIdMembersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPteamMembersPteamsPteamIdMembersGetError = GetPteamMembersPteamsPteamIdMembersGetErrors[keyof GetPteamMembersPteamsPteamIdMembersGetErrors];

export type GetPteamMembersPteamsPteamIdMembersGetResponses = {
    /**
     * Response Get Pteam Members Pteams  Pteam Id  Members Get
     *
     * Successful Response
     */
    200: Array<PteamMemberGetResponse>;
};

export type GetPteamMembersPteamsPteamIdMembersGetResponse = GetPteamMembersPteamsPteamIdMembersGetResponses[keyof GetPteamMembersPteamsPteamIdMembersGetResponses];

export type DeleteMemberPteamsPteamIdMembersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/members/{user_id}';
};

export type DeleteMemberPteamsPteamIdMembersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMemberPteamsPteamIdMembersUserIdDeleteError = DeleteMemberPteamsPteamIdMembersUserIdDeleteErrors[keyof DeleteMemberPteamsPteamIdMembersUserIdDeleteErrors];

export type DeleteMemberPteamsPteamIdMembersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMemberPteamsPteamIdMembersUserIdDeleteResponse = DeleteMemberPteamsPteamIdMembersUserIdDeleteResponses[keyof DeleteMemberPteamsPteamIdMembersUserIdDeleteResponses];

export type UpdatePteamMemberPteamsPteamIdMembersUserIdPutData = {
    body: PTeamMemberUpdateRequest;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/members/{user_id}';
};

export type UpdatePteamMemberPteamsPteamIdMembersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePteamMemberPteamsPteamIdMembersUserIdPutError = UpdatePteamMemberPteamsPteamIdMembersUserIdPutErrors[keyof UpdatePteamMemberPteamsPteamIdMembersUserIdPutErrors];

export type UpdatePteamMemberPteamsPteamIdMembersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: PTeamMemberUpdateResponse;
};

export type UpdatePteamMemberPteamsPteamIdMembersUserIdPutResponse = UpdatePteamMemberPteamsPteamIdMembersUserIdPutResponses[keyof UpdatePteamMemberPteamsPteamIdMembersUserIdPutResponses];

export type ListInvitationsPteamsPteamIdInvitationGetData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/invitation';
};

export type ListInvitationsPteamsPteamIdInvitationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInvitationsPteamsPteamIdInvitationGetError = ListInvitationsPteamsPteamIdInvitationGetErrors[keyof ListInvitationsPteamsPteamIdInvitationGetErrors];

export type ListInvitationsPteamsPteamIdInvitationGetResponses = {
    /**
     * Response List Invitations Pteams  Pteam Id  Invitation Get
     *
     * Successful Response
     */
    200: Array<PTeamInvitationResponse>;
};

export type ListInvitationsPteamsPteamIdInvitationGetResponse = ListInvitationsPteamsPteamIdInvitationGetResponses[keyof ListInvitationsPteamsPteamIdInvitationGetResponses];

export type CreateInvitationPteamsPteamIdInvitationPostData = {
    body: PTeamInvitationRequest;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/invitation';
};

export type CreateInvitationPteamsPteamIdInvitationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInvitationPteamsPteamIdInvitationPostError = CreateInvitationPteamsPteamIdInvitationPostErrors[keyof CreateInvitationPteamsPteamIdInvitationPostErrors];

export type CreateInvitationPteamsPteamIdInvitationPostResponses = {
    /**
     * Successful Response
     */
    200: PTeamInvitationResponse;
};

export type CreateInvitationPteamsPteamIdInvitationPostResponse = CreateInvitationPteamsPteamIdInvitationPostResponses[keyof CreateInvitationPteamsPteamIdInvitationPostResponses];

export type DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Pteam Id
         */
        pteam_id: string;
        /**
         * Invitation Id
         */
        invitation_id: string;
    };
    query?: never;
    url: '/pteams/{pteam_id}/invitation/{invitation_id}';
};

export type DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteError = DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteErrors[keyof DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteErrors];

export type DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteResponse = DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteResponses[keyof DeleteInvitationPteamsPteamIdInvitationInvitationIdDeleteResponses];

export type DeleteUserUsersMeDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type DeleteUserUsersMeDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserUsersMeDeleteResponse = DeleteUserUsersMeDeleteResponses[keyof DeleteUserUsersMeDeleteResponses];

export type GetMyUserInfoUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetMyUserInfoUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetMyUserInfoUsersMeGetResponse = GetMyUserInfoUsersMeGetResponses[keyof GetMyUserInfoUsersMeGetResponses];

export type CreateUserUsersPostData = {
    body: UserCreateRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type UpdateUserUsersUserIdPutData = {
    body: UserUpdateRequest;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPutError = UpdateUserUsersUserIdPutErrors[keyof UpdateUserUsersUserIdPutErrors];

export type UpdateUserUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserUsersUserIdPutResponse = UpdateUserUsersUserIdPutResponses[keyof UpdateUserUsersUserIdPutResponses];

export type DeleteVulnVulnsVulnIdDeleteData = {
    body?: never;
    headers: {
        /**
         * X-Api-Key
         */
        'x-api-key': string;
    };
    path: {
        /**
         * Vuln Id
         */
        vuln_id: string;
    };
    query?: never;
    url: '/vulns/{vuln_id}';
};

export type DeleteVulnVulnsVulnIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteVulnVulnsVulnIdDeleteError = DeleteVulnVulnsVulnIdDeleteErrors[keyof DeleteVulnVulnsVulnIdDeleteErrors];

export type DeleteVulnVulnsVulnIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteVulnVulnsVulnIdDeleteResponse = DeleteVulnVulnsVulnIdDeleteResponses[keyof DeleteVulnVulnsVulnIdDeleteResponses];

export type GetVulnVulnsVulnIdGetData = {
    body?: never;
    path: {
        /**
         * Vuln Id
         */
        vuln_id: string;
    };
    query?: never;
    url: '/vulns/{vuln_id}';
};

export type GetVulnVulnsVulnIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVulnVulnsVulnIdGetError = GetVulnVulnsVulnIdGetErrors[keyof GetVulnVulnsVulnIdGetErrors];

export type GetVulnVulnsVulnIdGetResponses = {
    /**
     * Successful Response
     */
    200: VulnResponse;
};

export type GetVulnVulnsVulnIdGetResponse = GetVulnVulnsVulnIdGetResponses[keyof GetVulnVulnsVulnIdGetResponses];

export type UpdateVulnVulnsVulnIdPutData = {
    body: VulnUpdateRequest;
    headers: {
        /**
         * X-Api-Key
         */
        'x-api-key': string;
    };
    path: {
        /**
         * Vuln Id
         */
        vuln_id: string;
    };
    query?: never;
    url: '/vulns/{vuln_id}';
};

export type UpdateVulnVulnsVulnIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateVulnVulnsVulnIdPutError = UpdateVulnVulnsVulnIdPutErrors[keyof UpdateVulnVulnsVulnIdPutErrors];

export type UpdateVulnVulnsVulnIdPutResponses = {
    /**
     * Successful Response
     */
    200: VulnResponse;
};

export type UpdateVulnVulnsVulnIdPutResponse = UpdateVulnVulnsVulnIdPutResponses[keyof UpdateVulnVulnsVulnIdPutResponses];

export type GetVulnsVulnsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Min Cvss V3 Score
         */
        min_cvss_v3_score?: number | null;
        /**
         * Max Cvss V3 Score
         */
        max_cvss_v3_score?: number | null;
        /**
         * Vuln Ids
         */
        vuln_ids?: Array<string> | null;
        /**
         * Title Words
         */
        title_words?: Array<string> | null;
        /**
         * Detail Words
         */
        detail_words?: Array<string> | null;
        /**
         * Creator Ids
         */
        creator_ids?: Array<string> | null;
        /**
         * Created After
         */
        created_after?: string | null;
        /**
         * Created Before
         */
        created_before?: string | null;
        /**
         * Updated After
         */
        updated_after?: string | null;
        /**
         * Updated Before
         */
        updated_before?: string | null;
        /**
         * Pteam Id
         */
        pteam_id?: string | null;
        /**
         * Cve Ids
         */
        cve_ids?: Array<string> | null;
        /**
         * Package Name
         */
        package_name?: Array<string> | null;
        /**
         * Ecosystem
         */
        ecosystem?: Array<string> | null;
        /**
         * Sort Keys
         */
        sort_keys?: Array<unknown>;
    };
    url: '/vulns';
};

export type GetVulnsVulnsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetVulnsVulnsGetError = GetVulnsVulnsGetErrors[keyof GetVulnsVulnsGetErrors];

export type GetVulnsVulnsGetResponses = {
    /**
     * Successful Response
     */
    200: VulnsListResponse;
};

export type GetVulnsVulnsGetResponse = GetVulnsVulnsGetResponses[keyof GetVulnsVulnsGetResponses];

export type GetTicketsTicketsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Assigned To Me
         */
        assigned_to_me?: boolean;
        /**
         * Pteam Ids
         */
        pteam_ids?: Array<string> | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Sort Keys
         */
        sort_keys?: Array<unknown>;
        /**
         * Exclude Statuses
         */
        exclude_statuses?: Array<TicketHandlingStatusType> | null;
        /**
         * Cve Ids
         */
        cve_ids?: Array<string> | null;
    };
    url: '/tickets';
};

export type GetTicketsTicketsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTicketsTicketsGetError = GetTicketsTicketsGetErrors[keyof GetTicketsTicketsGetErrors];

export type GetTicketsTicketsGetResponses = {
    /**
     * Successful Response
     */
    200: TicketListResponse;
};

export type GetTicketsTicketsGetResponse = GetTicketsTicketsGetResponses[keyof GetTicketsTicketsGetResponses];

export type DeleteInsightTicketsTicketIdInsightDeleteData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/tickets/{ticket_id}/insight';
};

export type DeleteInsightTicketsTicketIdInsightDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteInsightTicketsTicketIdInsightDeleteError = DeleteInsightTicketsTicketIdInsightDeleteErrors[keyof DeleteInsightTicketsTicketIdInsightDeleteErrors];

export type DeleteInsightTicketsTicketIdInsightDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteInsightTicketsTicketIdInsightDeleteResponse = DeleteInsightTicketsTicketIdInsightDeleteResponses[keyof DeleteInsightTicketsTicketIdInsightDeleteResponses];

export type GetInsightTicketsTicketIdInsightGetData = {
    body?: never;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/tickets/{ticket_id}/insight';
};

export type GetInsightTicketsTicketIdInsightGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInsightTicketsTicketIdInsightGetError = GetInsightTicketsTicketIdInsightGetErrors[keyof GetInsightTicketsTicketIdInsightGetErrors];

export type GetInsightTicketsTicketIdInsightGetResponses = {
    /**
     * Successful Response
     */
    200: InsightResponse;
};

export type GetInsightTicketsTicketIdInsightGetResponse = GetInsightTicketsTicketIdInsightGetResponses[keyof GetInsightTicketsTicketIdInsightGetResponses];

export type UpdateInsightTicketsTicketIdInsightPutData = {
    body: InsightUpdateRequest;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/tickets/{ticket_id}/insight';
};

export type UpdateInsightTicketsTicketIdInsightPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateInsightTicketsTicketIdInsightPutError = UpdateInsightTicketsTicketIdInsightPutErrors[keyof UpdateInsightTicketsTicketIdInsightPutErrors];

export type UpdateInsightTicketsTicketIdInsightPutResponses = {
    /**
     * Successful Response
     */
    200: InsightResponse;
};

export type UpdateInsightTicketsTicketIdInsightPutResponse = UpdateInsightTicketsTicketIdInsightPutResponses[keyof UpdateInsightTicketsTicketIdInsightPutResponses];

export type GetEolProductsEolsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Pteam Id
         *
         * PTeam ID (optional)
         */
        pteam_id?: string | null;
        /**
         * Eol Product Id
         *
         * EoL Product ID (optional)
         */
        eol_product_id?: string | null;
    };
    url: '/eols/';
};

export type GetEolProductsEolsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEolProductsEolsGetError = GetEolProductsEolsGetErrors[keyof GetEolProductsEolsGetErrors];

export type GetEolProductsEolsGetResponses = {
    /**
     * Successful Response
     */
    200: EoLProductListResponse;
};

export type GetEolProductsEolsGetResponse = GetEolProductsEolsGetResponses[keyof GetEolProductsEolsGetResponses];

export type DeleteEolEolsEolProductIdDeleteData = {
    body?: never;
    headers: {
        /**
         * X-Api-Key
         */
        'x-api-key': string;
    };
    path: {
        /**
         * Eol Product Id
         */
        eol_product_id: string;
    };
    query?: never;
    url: '/eols/{eol_product_id}';
};

export type DeleteEolEolsEolProductIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEolEolsEolProductIdDeleteError = DeleteEolEolsEolProductIdDeleteErrors[keyof DeleteEolEolsEolProductIdDeleteErrors];

export type DeleteEolEolsEolProductIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEolEolsEolProductIdDeleteResponse = DeleteEolEolsEolProductIdDeleteResponses[keyof DeleteEolEolsEolProductIdDeleteResponses];

export type UpdateEolEolsEolProductIdPutData = {
    body: EoLProductRequest;
    headers: {
        /**
         * X-Api-Key
         */
        'x-api-key': string;
    };
    path: {
        /**
         * Eol Product Id
         */
        eol_product_id: string;
    };
    query?: never;
    url: '/eols/{eol_product_id}';
};

export type UpdateEolEolsEolProductIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEolEolsEolProductIdPutError = UpdateEolEolsEolProductIdPutErrors[keyof UpdateEolEolsEolProductIdPutErrors];

export type UpdateEolEolsEolProductIdPutResponses = {
    /**
     * Successful Response
     */
    200: EoLProductResponse;
};

export type UpdateEolEolsEolProductIdPutResponse = UpdateEolEolsEolProductIdPutResponses[keyof UpdateEolEolsEolProductIdPutResponses];

export type InternalOpenapiSchemaInternalApiOpenapiJsonGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/internal-api/openapi.json';
};

export type InternalOpenapiSchemaInternalApiOpenapiJsonGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
