name: Lint GitHub Actions workflows
"on":
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color -verbose
        shell: bash
