name: lint scripts directory

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - main
    paths:
      - scripts/**
  push:
    branches:
      - main
    paths:
      - scripts/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.12"
  PYTHON_ROOT_DIRS: ./
  SCRIPTS_DIRS: ./scripts

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.SCRIPTS_DIRS }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Setup uv
        run: |
          pip install --user uv
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Create Python virtual environment
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev libpq-dev
          uv sync --locked --dev
        # Runs a linter for python
      - name: Run formatting check
        run: |
          uv run --locked black --check --diff ${{ env.PYTHON_ROOT_DIRS }}
          uv run --locked ruff check ${{ env.PYTHON_ROOT_DIRS }}
          uv run --locked mypy ${{ env.PYTHON_ROOT_DIRS }} --show-error-codes --no-error-summary
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: "fs"
          scan-ref: ${{ env.SCRIPTS_DIRS }}
          trivy-config: trivy.yaml
